### ISSUE TITLE
Autocompletion broken by package object wildcard import for scala >= 2.12.9

### ISSUE THREAD

**Issue by mpollmeier** [lihaoyi/Ammonite#1009]
This may be the root cause for other autocompletion-issues here. I was able to pin it down quite a bit (see below). But first, here's how to reproduce the issue:

```
def foobar = 123
foob<tab> //autocompletion works
import scala.math._
foob<tab> //tab completion broken
```

I.e. as soon as the user imports an entire package object, autocompletion breaks. 

Some facts to pin it down:
* other wildcard imports work fine, i.e. anything but package objects
* the imported package object can even be empty and still breaks autocompletion
* autocompletion stays broken for the entire session, i.e. you can't fix it by redefining `foobar` or new defs
* the regular scala repl is not affected
* this is independent of java version we're running with (unlike what's suggested in https://github.com/lihaoyi/Ammonite/issues/995)
* the last version of ammonite without this bug is `2.12-1.6.8-24-9a4ffa5`, which was built using scala 2.12.8
* when starting ammonite.Main from a scala main, I saw that it's only broken if ammonite is built with scala >= 2.12.9 (2.13.x is broken as well). However when using scala 2.12.8, even the latest ammonite version 1.7.4 works just fine

**Comment by alexarchambault** [comment]
Not really sure what the problem is yet, but this works:
```scala
@ def foobar = 123
@ foob<tab> //autocompletion works
@ import scala.math.{`package` => _, _}
@ foob<tab> //tab completion *works again*
```

**Comment by mpollmeier** [comment]
thanks for sharing, yes that workaround works (although it's ugly) and may help to find the root cause

**Comment by mpollmeier** [comment]
Just tested with `3.1-2.5.4-15-f4a8969b`: the scala3 repl is not affected - in fact the autocompletion works completely different there. It's probably inherited from the default presentation compiler / repl or whatever is used underneath. 

```
def foobar = 123
@ foob<tab> //no tab completion
@ foobar.<tab> //tab completion works
@ import scala.math._
@ foobar.<tab> //tab completion still works, i.e. is not affected by wildcard import
```

**Comment by szeiger** [comment]
I suspect this is the change that broke it: https://github.com/scala/scala/commit/e9bd65d7f84864ba16bde7b0537d60043798eb3f. It was also backported to 2.12.9.

Auto-completion being broken is just a side effect of a compiler error that is silently ignored. It also breaks when trying to compile the relevant part of the generated import statement directly:

```
@ import scala.math.`package`

  Can't rename a package object to package
     while compiling: cmd0.sc
        during phase: AmmonitePhase
...
```

These imports are allowed in Scala, both with and without renames, and the Scala REPL can compile them and offer auto-complete for package objects.

Notice that the error is in AmmonitePhase. It uses `allImportedSymbols` to find the symbol names:
```
        val symNames = for {
          sym <- info.allImportedSymbols
          if saneSym(sym)
        } yield {
          (sym.isType, sym.decodedName)
        }
```
Internally this leads to a `setName` call on a `PackageObjectClassSymbol` which is not allowed.

I wasn't able to debug this with a modified Scala compiler build because I have no idea how to make the Mill build for Ammonite work with a non-standard version. I can manually override the dependencies but then it doesn't find a compiler interface. Mill doesn't seem to recognize the snapshot version numbers generated by `setupPublishCore` as binary compatible.

A simple workaround for auto-completion is to skip the package imports in `Imports.toString`.

I'm not sure what the underlying bug is. The Scala REPL doesn't call `allImportedSymbols`. Is it expected to work in this context? Should this be considered a bug in scalac? Or does Ammonite need to use a different way to get the names? The latter looks like the best way out. Even if this is a bug in scalac, Ammonite would remain broken for all the versions that have been released since. It's not hard to reimplement the symbol names code without cloning the symbols.

It still doesn't work though. Autocomplete runs into the same issue in `getScopeCompletion`:
```
scala.reflect.internal.FatalError: Can't rename a package object to package
	at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.reflect.internal.Symbols$PackageObjectClassSymbol.setName(Symbols.scala:3554)
	at scala.reflect.internal.Symbols$PackageObjectClassSymbol.setName(Symbols.scala:3548)
	at scala.reflect.internal.Symbols$Symbol.cloneSymbol(Symbols.scala:2070)
	at scala.tools.nsc.typechecker.Contexts$ImportInfo.transformImport(Contexts.scala:1924)
	at scala.tools.nsc.typechecker.Contexts$ImportInfo.$anonfun$allImportedSymbols$1(Contexts.scala:1914)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:608)
	at scala.collection.immutable.List.prependedAll(List.scala:155)
	at scala.collection.immutable.List$.from(List.scala:684)
	at scala.collection.immutable.List$.from(List.scala:681)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:35)
	at scala.collection.immutable.Iterable$.from(Iterable.scala:32)
	at scala.collection.IterableFactory$Delegate.from(Factory.scala:288)
	at scala.collection.IterableOps.flatMap(Iterable.scala:684)
	at scala.collection.IterableOps.flatMap$(Iterable.scala:684)
	at scala.collection.AbstractIterable.flatMap(Iterable.scala:933)
	at scala.tools.nsc.typechecker.Contexts$ImportInfo.allImportedSymbols(Contexts.scala:1914)
	at scala.tools.nsc.interactive.Global.$anonfun$scopeMembers$4(Global.scala:1079)
	at scala.tools.nsc.interactive.Global.scopeMembers(Global.scala:1077)
	at scala.tools.nsc.interactive.Global.$anonfun$getScopeCompletion$2(Global.scala:995)
	at scala.tools.nsc.interactive.Global.$anonfun$respond$1(Global.scala:711)
	at scala.tools.nsc.interactive.Global.respondGradually(Global.scala:718)
	at scala.tools.nsc.interactive.Global.respond(Global.scala:711)
	at scala.tools.nsc.interactive.Global.getScopeCompletion(Global.scala:995)
```

I'm not that familiar with Ammonite. Does it do any tree transformations in custom compiler phases? I suppose the alternative is that this getScopeCompletion workflow is indeed broken and the Scala REPL uses a different method. Short of figuring this out we could go back to removing these problematic imports from the autocomplete snippets as shown above (in addition to fixing AmmonitePhase). This will prevent autocomplete from working for `package` imports (whether renamed or verbatim) but it should make everything else work again.

Here's a branch with the partial fix: https://github.com/com-lihaoyi/Ammonite/compare/main...szeiger:Ammonite:issue-1009

**Comment by lihaoyi** [comment]
Ammonite has two custom compiler phases in https://github.com/com-lihaoyi/Ammonite/blob/main/amm/compiler/src/main/scala-2/ammonite/compiler/AmmonitePlugin.scala:

1. Adjusts positions to restore the original line numbers, after the code wrapping takes place
2. Inspects the identifiers present at the end of every command and saves them, so future commands can set up the proper `import`s

I don't think any of those count as significant transfomations. Apart from those, all of Ammonite's code manipulation is textual: replacing `ivy imports` with stubs, performing the proper `import`s at the top of every command, wrapping expressions on top-level `object`s

It feels to me like the bug is in `allImportedSymbols`, which shouldn't crash. Having Ammonite ask the compiler for `allImportedSymbols` in order to figure out what needs importing in future commands and what identifiers can be auto-completed sounds like a very reasonable thing for Ammonite to do
