### ISSUE TITLE
Bug using sbt run script (using cs command)  scalas

### ISSUE THREAD

**Issue by reyman** [lihaoyi/Ammonite#11]
Hi,

I try to use Ammonite with conscript cs command tool (https://github.com/n8han/conscript) to run scala script as SBT manual say ( http://www.scala-sbt.org/0.13/docs/Combined+Pages.html )

```scala
#!/usr/bin/env scalas

/***
scalaVersion := "2.11.5"

resolvers += Resolver.url("Sonatype OSS Snapshots",url("https://oss.sonatype.org/content/repositories/snapshots"))(Resolver.ivyStylePatterns)

libraryDependencies += "com.lihaoyi" %% "ammonite" % "0.1.4"
*/

import ammonite.all._

val wd = processWorkingDir

ls! wd
```

I have this error :

```
[info] Loading global plugins from /home/srey/.sbt/0.13/plugins
[info] Set current project to root-68794879dd0af3f5dec3 (in build file:/home/srey/.conscript/boot/68794879dd0af3f5dec3/)
[error] (run-main-0) java.lang.NoSuchMethodError: java.nio.file.Files.list(Ljava/nio/file/Path;)Ljava/util/stream/Stream;
java.lang.NoSuchMethodError: java.nio.file.Files.list(Ljava/nio/file/Path;)Ljava/util/stream/Stream;
	at ammonite.ops.ls$.apply(Ops.scala:173)
	at ammonite.ops.ls$.apply(Ops.scala:170)
	at ammonite.ops.Op1$class.$bang(Ops.scala:79)
	at ammonite.ops.ls$.$bang(Ops.scala:170)
	at convert_svg$$anon$1.<init>(convert_svg.scala:15)
	at convert_svg$.main(convert_svg.scala:2)
	at convert_svg.main(convert_svg.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
```

**Comment by lihaoyi** [comment]
Yeah it requires Java 7 and above, and it looks like you're using Java 6. Not likely to change unfortunately

**Comment by reyman** [comment]
Uh ? no, i use java 7 

java version "1.7.0_76"
Java(TM) SE Runtime Environment (build 1.7.0_76-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.76-b04, mixed mode)

**Comment by lihaoyi** [comment]
lol, it turns out it was introduced in Java 8

http://stackoverflow.com/questions/23957425/java-lang-nosuchmethoderror-on-raspberry-pi-only

Can you upgrade? If not, you can use the workaround suggested in the linked question. Feel free to send a PR if you want it in trunk

**Comment by reyman** [comment]
Ok, it's resolved with java 8 :) 
Thanks
