### ISSUE TITLE
Autocomplete crasher

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#128]
```
/Users/haoyi/Dropbox (Personal)/Workspace/Ammonite@ ls! .idea<tab>
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed: size=0 and step=0, but both must be positive
java.lang.IllegalArgumentException: requirement failed: size=0 and step=0, but both must be positive
	at scala.collection.Iterator$GroupedIterator.<init>(Iterator.scala:881)
	at scala.collection.Iterator$class.grouped(Iterator.scala:1018)
	at scala.collection.AbstractIterator.grouped(Iterator.scala:1194)
	at scala.collection.IterableLike$class.grouped(IterableLike.scala:174)
	at scala.collection.AbstractIterable.grouped(Iterable.scala:54)
	at ammonite.repl.frontend.FrontEnd$Ammonite$.tabulate(FrontEnd.scala:43)
	at ammonite.repl.frontend.FrontEnd$Ammonite$$anonfun$1.applyOrElse(FrontEnd.scala:105)
	at ammonite.repl.frontend.FrontEnd$Ammonite$$anonfun$1.applyOrElse(FrontEnd.scala:78)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.FilterTools$$anon$1.applyOrElse(FilterTools.scala:12)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.FilterTools$$anon$1.applyOrElse(FilterTools.scala:12)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.FilterTools$$anon$1.applyOrElse(FilterTools.scala:12)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.AdvancedFilters$SelectionFilter.applyOrElse(AdvancedFilters.scala:11)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at ammonite.terminal.TermCore$.rec$1(TermCore.scala:171)
	at ammonite.terminal.TermCore$.readLine(TermCore.scala:206)
	at ammonite.repl.frontend.FrontEnd$Ammonite$.readLine(FrontEnd.scala:128)
	at ammonite.repl.frontend.FrontEnd$Ammonite$.action(FrontEnd.scala:60)
	at ammonite.repl.Repl.action(Repl.scala:38)
	at ammonite.repl.Repl.loop$1(Repl.scala:57)
	at ammonite.repl.Repl.run(Repl.scala:70)
	at ammonite.repl.Repl$.run(Repl.scala:122)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:112)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:112)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:112)
	at ammonite.repl.Repl.main(Repl.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
[trace] Stack trace suppressed: run last repl/compile:run for the full output.
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at scala.tools.nsc.util.WorkScheduler.waitForMoreWork(WorkScheduler.scala:16)
	at scala.tools.nsc.interactive.PresentationCompilerThread$$anonfun$run$1.apply$mcZ$sp(PresentationCompilerThread.scala:21)
	at scala.tools.nsc.interactive.NullLogger$.logreplay(Replayer.scala:38)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:21)
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last repl/compile:run for the full output.
[error] (repl/compile:run) Nonzero exit code: 1
[error] Total time: 26 s, completed Jul 29, 2015 9:31:28 AM
haoyi-mbp:Ammonite haoyi$
```

**Comment by lihaoyi** [comment]
Seems to have gone away on its own (???)
