### ISSUE TITLE
Exception when starting from Windows git bash

### ISSUE THREAD

**Issue by tyrcho** [lihaoyi/Ammonite#141]
I have installed with `curl -L -o amm https://git.io/vO6Lo` 

I'm missing hints in the doc or the error message to solve the issue ...

```
$ ./amm
Loading Ammonite Repl...
Exception in thread "main" scala.reflect.internal.MissingRequirementError: objec
t java.lang.Object in compiler mirror not found.
        at scala.reflect.internal.MissingRequirementError$.signal(MissingRequire
mentError.scala:17)
        at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequi
rementError.scala:18)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.sca
la:53)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.sca
la:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.sca
la:45)
        at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.sca
la:66)
        at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala
:102)
        at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.sca
la:105)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzyco
mpute(Definitions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Defin
itions.scala:257)
        at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.
scala:1394)
        at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
        at ammonite.repl.interp.Compiler$$anon$4.<init>(Compiler.scala:142)
        at ammonite.repl.interp.Compiler$.apply(Compiler.scala:120)
        at ammonite.repl.interp.Interpreter.init(Interpreter.scala:225)
        at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:265)
        at ammonite.repl.Repl.<init>(Repl.scala:28)
        at ammonite.repl.Repl$.repl$1(Repl.scala:138)
        at ammonite.repl.Repl$.run(Repl.scala:146)
        at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:130)
        at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:130)
        at scala.Option.foreach(Option.scala:257)
        at ammonite.repl.Repl$.main(Repl.scala:130)
        at ammonite.repl.Repl.main(Repl.scala)

tyrcho@TYRCHO-PC /C/Users/tyrcho
```

**Comment by tyrcho** [comment]
I have the same stack if I download 0.4.2 and start it with java -jar

**Comment by lihaoyi** [comment]
Merged with https://github.com/lihaoyi/Ammonite/issues/119
