### ISSUE TITLE
Ammonite-REPL 0.4.5 startup fails with "MissingRequirementError" on OpenJDK 8 (Ubuntu 15.N linux)

### ISSUE THREAD

**Issue by LeeTibbert** [lihaoyi/Ammonite#168]
The fix for #148 appears to work for me with OpenJDK 7 (lxc container running Ubuntu Wily (15.10)).
With OpenJDK 8 (i686 running Ubuntu 15.04), I get the same error as #148:

    Exception in thread "main" scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
	at ammonite.repl.interp.Compiler$$anon$4.<init>(Compiler.scala:191)
	at ammonite.repl.interp.Compiler$.apply(Compiler.scala:120)
	at ammonite.repl.interp.Interpreter.init(Interpreter.scala:234)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:275)
	at ammonite.repl.Repl.<init>(Repl.scala:26)
	at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:166)
	at ammonite.repl.Repl$.repl$1(Repl.scala:166)
	at ammonite.repl.Repl$.run(Repl.scala:174)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:142)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:142)
	at ammonite.repl.Repl.main(Repl.scala)

Looks like this gives me an excuse to figure out how to turn on a Logger and
see what Ammonite is unhappy about. Probably another .jar file to be filtered
out.  A comment to #148 gave a clue on logging, I need to follow that clue
to expand my knowledge/experience.

From the change history, I understand that Travis can not test OpenJDK 8.
Leave it to the path that can not be automatically tested to have problems ;-)

Thanks to all for the fix so far.

Lee

**Comment by LeeTibbert** [comment]
Rats!  I got Ammonite 0.4.5 to work with OpenJDK 8 (headless) in the
Wily (15.10) LXC container (where it had been working with OpenJDK 7).

    Loading...
   Welcome to the Ammonite Repl 0.4.5
  (Scala version 2.11.7 Java 1.8.0_66-internal)

This still fails on my (hardware) Ubuntu 15.04 system. May be an OpenJDK version
or headless vs Server issue: 

    Welcome to Scala version 2.11.7 (OpenJDK Server VM, Java 1.8.0_45-internal)

I have checked that ~/.ammonite does not exist.  I will keep my eye out for other
hanging cruft.

Next time I have time to take a run at this, I'll try to figure out how to get Logging
to work.

Lee

**Comment by lihaoyi** [comment]
Note that if you're "dev"-ing this, using Ammonite at part of an SBT project (even it's own, via `repl/run`) has a different failure modes w.r.t. classpath rubbish than running it via the standalone executable; worth trying both

**Comment by LeeTibbert** [comment]
Late_night/early_morning progress report:

In #148, @jrudolph identified a/the malefactor as:
  /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext/libatk-wrapper.so 

@lihaoyi 's Commit [334a7d5](
https://github.com/lihaoyi/Ammonite/commit/334a7d53f2e459967af37c5bf9f13d5b137071af) looks like it should filter this out:

      x => x.isFile && !x.getName.endsWith(".so") && !x.getName.endsWith(".jnilib")

I discovered that I had a libatk-wrapper.so in /jre/lib/ext/ on the Java 8 machine that was broken
and did not have one on the (simpler) machine that was working.  So, I took the .so out
of the chain (by creating a subdirectory & moving the .so into it).  The previously broken Java 8 machine gets to the @ prompt with both amm & sbt repl/run.  Yeah!  Not a solution but definitely a waypoint. Because of the hour, I have not yet run the tests to see if they all pass.

Seems like libatk-wrapper.so is used for assistive technologies. I suspect that someone
in the full Ubuntu desktop adds that file.  Moving it out of the way is a short term solution.

Next activity cycle or so, I hope to temporarily restore the offending .so & see why the
code above does not filter it out (or how it creeps in somewhere else).  I still need to get Logging working, to ease my life. All good things in time.

**Comment by LeeTibbert** [comment]
re: failure modes.

Thank you for the heads up!

**Comment by LeeTibbert** [comment]
Seems like all is well here now.  Rebooting and using a freshly fetched amm standalone
& freshly fetched & locally built ammonite-master shows both getting to the @ prompt
with OpenJDK 8.

I restored libatk-wrapper.so to its original place to see if I could restore the
broken condition I originally encountered. Both amm & sbt repl/run confinued
to work.  I do not know if I caught the code in the midst of change (does not
look like it), or caches in the midst of change,  or if I simply got massively 
confused chasing my tail debugging.  (In all cases, I did a rm -rf ~/,ammonite
to start fresh)

My apologies for any confusion I may have spread...

I will use Ammonite in my work for the next few days and
close this issue if I can not reproduce and no one else
reports experiencing this.

**Comment by metasim** [comment]
FYI: I'm getting the same error on MacOS with JDK 8:

*Java*:

```
 java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

*Ammonite*:

```
amm -version
Error: Unknown option -version
ammonite 0.4.5

```

*Error*:

```
Exception in thread "main" scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
	at ammonite.repl.interp.Compiler$$anon$4.<init>(Compiler.scala:191)
	at ammonite.repl.interp.Compiler$.apply(Compiler.scala:120)
	at ammonite.repl.interp.Interpreter.init(Interpreter.scala:234)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:275)
	at ammonite.repl.Repl.<init>(Repl.scala:26)
...
```

**Comment by jrudolph** [comment]
To debug issues like that applying this diff will increase logging output:

```diff
diff --git a/repl/src/main/scala/ammonite/repl/interp/Compiler.scala b/repl/src/main/scala/ammonite/repl/interp/Compiler.scala
index 86322be..88aaf95 100644
--- a/repl/src/main/scala/ammonite/repl/interp/Compiler.scala
+++ b/repl/src/main/scala/ammonite/repl/interp/Compiler.scala
@@ -89,6 +89,7 @@ object Compiler{
     lazy val settings = new Settings
     val settingsX = settings
     settingsX.Yrangepos.value = true
+    settings.Ylogcp.value = true
     val jCtx = new JavaContext()
     val jDirs = jarDeps.map(x =>
       new DirectoryClassPath(new FileZipArchive(x), jCtx)
@@ -96,6 +97,10 @@ object Compiler{
       new DirectoryClassPath(new PlainDirectory(new Directory(x)), jCtx)
     ) ++ Seq(new DirectoryClassPath(dynamicClasspath, jCtx))
     val jcp = new JavaClassPath(jDirs, jCtx)
+    println("jardeps")
+    jarDeps.foreach(p => println(s"${p.getName.takeRight(4)} $p"))
+    println("finished")
+
     settings.outputDirs.setSingleOutput(vd)
 
     val reporter = new AbstractReporter {
@@ -103,7 +108,9 @@ object Compiler{
 
       def display(pos: Position, msg: String, severity: Severity) = {
         severity match{
-          case ERROR => logger(Position.formatMessage(pos, msg, false))
+          case ERROR =>
+            println(s"ERROR: $msg")
+            logger(Position.formatMessage(pos, msg, false))
           case _ => logger(msg)
         }
       }
```

**Comment by lihaoyi** [comment]
Closing for now, @metasim feel free to re-open if you want to help debug and fix

**Comment by jportway** [comment]
Hi - has this been fixed?
I'm seeing this problem with a fresh install of Ammonite (first time I've had a look at it) with Oracle JDK 1.8.0_60-b27 installed on OSX

**Comment by tfb662** [comment]
https://github.com/lihaoyi/Ammonite/commit/334a7d53f2e459967af37c5bf9f13d5b137071af contains the following fix for linux
`  x => x.isFile && !x.getName.endsWith(".so") && !x.getName.endsWith(".jnilib")`
but it should also filter out ".dylib' for OSX.

**Comment by jportway** [comment]
If that's already in the master branch then it wasn't working. I'm not 100% sure but it's possible you might need to add ".dylib" to the list for OSX. I'll try it.

**Comment by jportway** [comment]
no - adding "dylib" to that list didn't help. I'm sorry that I don't have any time right now to investigate further.

**Comment by jrudolph** [comment]
Try adding the above lines from the diff which may be enough to find out which file is making trouble.

**Comment by holgerbrandl** [comment]
Both the installer and the sbt-inclusion via build.sbt fail on MacOS (10.10.5) with this (same as reported above) error:

```
[ammonite]$ curl -L -o amm http://git.io/vnnBX; chmod +x amm; ./amm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   587    0   587    0     0    656      0 --:--:-- --:--:-- --:--:--  1290
100 29.3M  100 29.3M    0     0  2636k      0  0:00:11  0:00:11 --:--:-- 3302kcd
Loading...
Exception in thread "main" scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
```

The java version does not seem to be the problem. It fails for oracle java 1.8.0_40 8 and 1.7.0_71.

I've tried the same under linux using openjdk-7 and it works. It looks pretty cool there, and it would be awesome to fix it for macos as well.

**Comment by jrudolph** [comment]
@holgerbrandl @jportway Can you try if my fix in #247 is more reliable?

**Comment by holgerbrandl** [comment]
I've tested it with

```
git clone https://github.com/jrudolph/Ammonite.git ammo_jr
cd ammo_jr
sbt ~repl/run 
```

However, the error still pops up and looks the same. I've no real clue how sbt works yet, so just let me know if there's a better way to test a potential fix.

I've tried the same with https://github.com/lihaoyi/Ammonite but no luck there as well.

**Comment by jrudolph** [comment]
You need to checkout the right branch, try

```
git co origin/w/robust-jar-probing
```

before running sbt.

**Comment by holgerbrandl** [comment]
uups, my bad. The awesome news is that the fix seems to work. 

There's just a warning (plus some deprecation infos):
```
/Users/brandl/Desktop/ammo_jr/repl/src/main/scala/ammonite/repl/Repl.scala:192: match may not be exhaustive.
[warn] It would fail on the following input: (Some(_), Some(_))
[warn]     (file, code) match{
[warn]     ^
```
but I think it might be unrelated.

It would be great if this fix could make it into the release.

**Comment by jportway** [comment]
@jrudolph works for me too.
Thanks!

**Comment by mfirry** [comment]
Hi,
I've stumbled on this problem with a fresh installation of `ammonite` on my Macbook Pro (10.10.5)

```
❯ amm -v
Error: Unknown option -v
ammonite 0.4.8
Usage: ammonite [options] [<file>...]
```
and
```
❯ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

First line of error is: `Exception in thread "main" scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.`

**Comment by Jentsch** [comment]
Had the same issue on (K)ubuntu. The branch origin/w/robust-jar-probing from jrudolph fixed the problem for me. May be this issue should be reopened.

**Comment by lihaoyi** [comment]
I'll take a look at this next pass through Ammonite

**Comment by etorreborre** [comment]
:+1:  thanks for having a look at this.

**Comment by gavinbaumanis** [comment]
Thanks for lre-looking into this.
I really do look forward to trying it out!
