### ISSUE TITLE
Problem with scala.concurrent.duration usage.

### ISSUE THREAD

**Issue by dant3** [lihaoyi/Ammonite#188]
Hi. I tried to create `FiniteDuration` instance in ammonite but never found a way how can I currently do this. Whenever I try to use anything related to `scala.concurrent.duration.TimeUnit` I get something like this:
```scala
> ammonite
Loading...
Welcome to the Ammonite Repl 0.4.5
(Scala version 2.11.7 Java 1.8.0_40)
@ val timeout = scala.concurrent.duration.Duration.apply(10, scala.concurrent.duration.SECONDS)
Compilation Failed
Main.scala:58: exception during macro expansion: 
scala.ScalaReflectionException: value NANOSECONDS is not a type
	at scala.reflect.api.Symbols$SymbolApi$class.asType(Symbols.scala:183)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asType(Symbols.scala:84)
	at derive.Derive$$anonfun$impl$1$2.apply(Derive.scala:75)
	at derive.Derive$$anonfun$impl$1$2.apply(Derive.scala:74)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at derive.Derive.impl$1(Derive.scala:74)
	at derive.Derive.fleshedOutSubtypes(Derive.scala:81)
	at derive.Derive.derive$Derive$$onFail$1(Derive.scala:136)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:204)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:178)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at derive.Derive.derive$Derive$$rec$1(Derive.scala:178)
	at derive.Derive$$anonfun$5.apply(Derive.scala:157)
	at derive.Derive$$anonfun$5.apply(Derive.scala:157)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at derive.Derive.derive$Derive$$onFail$1(Derive.scala:157)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:204)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:178)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at derive.Derive.derive$Derive$$rec$1(Derive.scala:178)
	at derive.Derive.deriveType(Derive.scala:217)
	at derive.Derive.derive(Derive.scala:58)
	at pprint.Internals$LowerPriPPrint$.liftedTree1$1(PPrint.scala:398)
	at pprint.Internals$LowerPriPPrint$.FinalRepr(PPrint.scala:398)

        def $main() = { ammonite.repl.frontend.ReplBridge.repl.Internal.combinePrints(ammonite.repl.frontend.ReplBridge.repl.Internal.print(timeout, timeout, "timeout", None)) }
                                                                                                                                           ^
```

**Comment by lihaoyi** [comment]
Looks like it's the same problem as https://github.com/lihaoyi/Ammonite/issues/186, so let's focus the discussion there
