### ISSUE TITLE
bare repl exits with stacktrace on every command

### ISSUE THREAD

**Issue by aberezin** [lihaoyi/Ammonite#212]
I have created a fresh, bare Ammonite on OSX 10.10.5 running OS X bash 3.2.57
JDK 1.8.0_45 and Scala 2.11.7

Anything I enter on the cmd line causes the repl to exit with a stack trace.  I have installed the repl on an Ubuntu box and do not have a problem.  Here is the terminal session on the osx iTerm. Note I entered *val x=1* on the cmd line in the example below. 

```bash
(py278)bin $ version
10.10.5
(py278)bin $ echo $BASH_VERSION
3.2.57(1)-release
(py278)bin $ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
(py278)bin $ scala -version
Scala code runner version 2.11.7 -- Copyright 2002-2013, LAMP/EPFL
(py278)bin $ sbt --version
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
sbt launcher version 0.13.7
(py278)bin $ rm -rf ~/.ammonite
(py278)bin $ curl -L -o amm http://git.io/vZJoU; chmod +x amm; ./amm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   404    0   404    0     0    567      0 --:--:-- --:--:-- --:--:--   567
100 29.3M  100 29.3M    0     0  4499k      0  0:00:06  0:00:06 --:--:-- 6145k
Loading...
Welcome to the Ammonite Repl 0.4.7
(Scala 2.11.7 Java 1.8.0_45)
@ val x=1
stty: standard input: unable to perform all requested operations
Exception in thread "main" java.lang.RuntimeException: Nonzero exit value: 1
	at scala.sys.package$.error(package.scala:27)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
	at ammonite.terminal.TTY$.stty(Utils.scala:78)
	at ammonite.terminal.TermCore$.readLine(TermCore.scala:240)
	at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:114)
	at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:25)
	at ammonite.repl.Repl.action(Repl.scala:45)
	at ammonite.repl.Repl.loop$1(Repl.scala:78)
	at ammonite.repl.Repl.run(Repl.scala:96)
	at ammonite.repl.Repl$.run(Repl.scala:195)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
```

**Comment by jvr-ks** [comment]
I get the same error on Windows 7 with Scala 2.11.7 and Java 1.8.0_60

[info] Starting scala interpreter...
[info]
Loading...
Welcome to the Ammonite Repl 0.4.8
(Scala 2.11.7 Java 1.8.0_60)
java.lang.RuntimeException: Nonzero exit value: 127
  at scala.sys.package$.error(package.scala:27)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
  at ammonite.terminal.TTY$.consoleDim(Utils.scala:54)
  at ammonite.terminal.TTY$.init(Utils.scala:59)
  at ammonite.terminal.TermCore$.x$6$lzycompute$1(TermCore.scala:230)
  at ammonite.terminal.TermCore$.x$6$1(TermCore.scala:230)
  at ammonite.terminal.TermCore$.initialConfig$lzycompute$1(TermCore.scala:230)
  at ammonite.terminal.TermCore$.initialConfig$1(TermCore.scala:230)
  at ammonite.terminal.TermCore$.readLine(TermCore.scala:240)
  at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:114)
  at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:25)
  at ammonite.repl.Repl.action(Repl.scala:45)
  at ammonite.repl.Repl.loop$1(Repl.scala:78)
  at ammonite.repl.Repl.run(Repl.scala:96)
  at ammonite.repl.Repl$.run(Repl.scala:195)
  ... 36 elided
Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions to have them evaluated.
Type :help for more information.

**Comment by s4nk** [comment]
Same here, Ammonite REPL 0.4.8, Scala 2.11.7, Java 1.7.0_79

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/Ammonite/pull/269
