### ISSUE TITLE
import from module + load.ivy in predef.scala

### ISSUE THREAD

**Issue by tylerprete** [lihaoyi/Ammonite#218]
With ammonite 0.4.7, jdk8.

In my predef.scala:
```
load.ivy("org.json4s" %% "json4s-jackson" % "3.2.11")

import org.json4s._
import org.json4s.jackson.JsonMethods._
import org.json4s.JsonDSL._
implicit val formats = org.json4s.DefaultFormats
```

I'm hitting this:
```
Loading...
Exception in thread "main" ammonite.repl.CompilationError: Compilation Failed
Main.scala:42: object json4s is not a member of package org
;import org.json4s._;import org.json4s.jackson.JsonMethods._;import org.json4s.JsonDSL._;implicit val formats = { () =>
            ^
Main.scala:42: object json4s is not a member of package org
;import org.json4s._;import org.json4s.jackson.JsonMethods._;import org.json4s.JsonDSL._;implicit val formats = { () =>
                                ^
Main.scala:42: object json4s is not a member of package org
;import org.json4s._;import org.json4s.jackson.JsonMethods._;import org.json4s.JsonDSL._;implicit val formats = { () =>
                                                                        ^
Main.scala:43: object json4s is not a member of package org
org.json4s.DefaultFormats
    ^
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:138)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:121)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:95)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:338)
	at ammonite.repl.Repl.<init>(Repl.scala:28)
	at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:187)
	at ammonite.repl.Repl$.repl$1(Repl.scala:187)
	at ammonite.repl.Repl$.run(Repl.scala:195)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
```

Independently, I find load.ivy works fine, and import of other modules (like Either) works fine, but you can't import from things you've loaded freshly with load.ivy.

Any idea of a workaround?

**Comment by lihaoyi** [comment]
Can you try adding a `@` to break your `predef.scala` into two compilation units:

```scala
load.ivy("org.json4s" %% "json4s-jackson" % "3.2.11")
@
import org.json4s._
import org.json4s.jackson.JsonMethods._
import org.json4s.JsonDSL._
implicit val formats = org.json4s.DefaultFormats
```

I wrote some stuff about it here http://lihaoyi.github.io/Ammonite/#ScriptFiles, but maybe it could be put in a more prominent place

**Comment by tylerprete** [comment]
That works! Ok, so @ forces a compile. Makes sense now. Awesome, thanks @lihaoyi!.
