### ISSUE TITLE
java.nio.file.NotDirectoryException

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/Ammonite#229]
Deleting a filethat doesn't exist using `rm`  (maybe in a folder that doesn't exist) throws the following exception in 0.4.6. Problem gone in 0.4.7. Is there a test that prevent a regression here?

```
java.nio.file.NotDirectoryException: /Users/user/foo.txt
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:406)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at ammonite.ops.ls$.$bang$bang(FileOps.scala:228)
	at ammonite.ops.ls$rec$.ammonite$ops$ls$rec$$these$1(FileOps.scala:243)
	at ammonite.ops.ls$rec$.recursiveListFiles(FileOps.scala:244)
	at ammonite.ops.ls$rec$.$bang$bang(FileOps.scala:247)
	at ammonite.ops.ls$rec$.$bang$bang(FileOps.scala:240)
	at ammonite.ops.StreamableOp1$class.apply(FileOps.scala:120)
	at ammonite.ops.ls$rec$.apply(FileOps.scala:240)
	at ammonite.ops.rm$.apply(FileOps.scala:174)
```

**Comment by lihaoyi** [comment]
Good question, maybe this one? https://github.com/lihaoyi/Ammonite/blame/master/ops/src/test/scala/test/ammonite/ops/OpTests.scala#L51 I don't remember honestly.

You should probably also ask on the gitter channel if you're not sure. This isn't really an issue afaict
