### ISSUE TITLE
tab completion on "import scala.concurrent.ExecutionContext.global." exits ammonite

### ISSUE THREAD

**Issue by phdoerfler** [lihaoyi/Ammonite#255]
How to reproduce:

```scala
$ amm
Loading...
Welcome to the Ammonite Repl 0.4.8
(Scala 2.11.7 Java 1.8.0_45)
@ import scala.concurrent._
import scala.concurrenimport scala.concurrent._

@ import scala.concurrent.ExecutionContext.global.<TAB>
```

this causes this exception and then quits ammonite:
```scala
@ import scala.concurrent.ExecutionContext.global.Exception in thread "main" java.lang.ClassCastException: scala.reflect.internal.Trees$Select cannot be cast to scala.reflect.internal.Trees$Ident
	at ammonite.repl.interp.Pressy$Run.prefixed(Pressy.scala:125)
	at ammonite.repl.interp.Pressy$$anon$3.complete(Pressy.scala:217)
	at ammonite.repl.Repl$$anonfun$action$1.apply(Repl.scala:51)
	at ammonite.repl.Repl$$anonfun$action$1.apply(Repl.scala:51)
	at ammonite.repl.frontend.AmmoniteFrontEnd$$anonfun$1.applyOrElse(AmmoniteFrontEnd.scala:54)
	at ammonite.repl.frontend.AmmoniteFrontEnd$$anonfun$1.applyOrElse(AmmoniteFrontEnd.scala:52)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.FilterTools$$anon$1.applyOrElse(FilterTools.scala:12)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.FilterTools$$anon$1.applyOrElse(FilterTools.scala:12)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.FilterTools$$anon$1.applyOrElse(FilterTools.scala:12)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at ammonite.terminal.GUILikeFilters$SelectionFilter.applyOrElse(GUILikeFilters.scala:15)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at ammonite.terminal.TermCore$.readChar$1(TermCore.scala:200)
	at ammonite.terminal.TermCore$.readLine(TermCore.scala:232)
	at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:114)
	at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:25)
	at ammonite.repl.Repl.action(Repl.scala:45)
	at ammonite.repl.Repl.loop$1(Repl.scala:78)
	at ammonite.repl.Repl.run(Repl.scala:96)
	at ammonite.repl.Repl$.run(Repl.scala:195)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
```

**Comment by lihaoyi** [comment]
Closing in favor of https://github.com/lihaoyi/Ammonite/issues/275

**Comment by lihaoyi** [comment]
This seems to no longer exit ammonite in `master`, but still doesn't properly provide completions
