### ISSUE TITLE
`~repl/run` fails on a fresh checkout

### ISSUE THREAD

**Issue by Blaisorblade** [lihaoyi/Ammonite#256]
FYI, on a fresh checkout from ba949ec7c515fda5ba09a4b65100b18afab25510 `sbt ~repl/run` fails repeatedly. It seems it's trying to download `ammonite-shell` from some Ivy repository?

I'm sure I could workaround this by building and installing it locally, so it's a small regression, but maybe this could be avoided through an extra integration test?

```
$ sbt ~repl/run
[info] Loading global plugins from /Users/pgiarrusso/.sbt/0.13/plugins
[info] Loading project definition from /Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/project
[info] Updating {file:/Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/project/}ammonite-tatooine-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.eed3si9n/sbt-assembly/scala_2.10/sbt_0.13/0.13.0/jars/sbt-assembly.jar ...
[info] 	[SUCCESSFUL ] com.eed3si9n#sbt-assembly;0.13.0!sbt-assembly.jar (1903ms)
[info] downloading https://repo1.maven.org/maven2/com/lihaoyi/scalatex-sbt-plugin_2.10_0.13/0.3.1/scalatex-sbt-plugin-0.3.1.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#scalatex-sbt-plugin;0.3.1!scalatex-sbt-plugin.jar (484ms)
[info] downloading https://jcenter.bintray.com/org/scalactic/scalactic_2.10/2.2.1/scalactic_2.10-2.2.1.jar ...
[info] 	[SUCCESSFUL ] org.scalactic#scalactic_2.10;2.2.1!scalactic_2.10.jar(bundle) (454ms)
[info] Done updating.
[info] Compiling 1 Scala source to /Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to ammonite-tatooine (in build file:/Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/)
[info] Updating {file:/Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/}ops...
[info] Updating {file:/Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/}terminal...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://jcenter.bintray.com/com/lihaoyi/utest_2.11/0.3.0/utest_2.11-0.3.0.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#utest_2.11;0.3.0!utest_2.11.jar (2020ms)
[info] downloading https://jcenter.bintray.com/org/scala-lang/scala-reflect/2.11.4/scala-reflect-2.11.4.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.4!scala-reflect.jar (654ms)
[info] downloading https://jcenter.bintray.com/com/lihaoyi/acyclic_2.11/0.1.3/acyclic_2.11-0.1.3.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#acyclic_2.11;0.1.3!acyclic_2.11.jar (413ms)
[info] Done updating.
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Updating {file:/Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/}repl...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://jcenter.bintray.com/com/lihaoyi/pprint_2.11/0.3.6/pprint_2.11-0.3.6.jar ...
[info] 	[SUCCESSFUL ] com.lihaoyi#pprint_2.11;0.3.6!pprint_2.11.jar (500ms)
[info] downloading https://jcenter.bintray.com/com/chuusai/shapeless_2.11/2.1.0/shapeless_2.11-2.1.0.jar ...
[info] 	[SUCCESSFUL ] com.chuusai#shapeless_2.11;2.1.0!shapeless_2.11.jar(bundle) (7673ms)
[info] Done updating.
[info] Compiling 7 Scala sources to /Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/ops/target/scala-2.11/classes...
[info] Compiling 9 Scala sources to /Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/terminal/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.7. Compiling...
[info]   Compilation completed in 11.165 s
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] there were 24 feature warnings; re-run with -feature for details
[warn] two warnings found
[info] Compiling 23 Scala sources to /Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/repl/target/scala-2.11/classes...
[warn] /Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/repl/src/main/scala/ammonite/repl/Repl.scala:192: match may not be exhaustive.
[warn] It would fail on the following input: (Some(_), Some(_))
[warn]     (file, code) match{
[warn]     ^
[warn] there were 10 deprecation warnings; re-run with -deprecation for details
[warn] there were 7 unchecked warnings; re-run with -unchecked for details
[warn] there were 7 feature warnings; re-run with -feature for details
[warn] four warnings found
[info] Running ammonite.repl.Repl
Loading...
:: loading settings :: url = jar:file:/Users/pgiarrusso/.ivy2/cache/org.apache.ivy/ivy/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: com.lihaoyi#ammonite-shell_2.11-caller;working
	confs: [default]

:: problems summary ::
:::: WARNINGS
		module not found: com.lihaoyi#ammonite-shell_2.11;0.4.9-SNAPSHOT

	==== cache: tried

	  /Users/pgiarrusso/.ivy2/cache/com.lihaoyi/ammonite-shell_2.11/jars/ivy-0.4.9-SNAPSHOT.xml

	  -- artifact com.lihaoyi#ammonite-shell_2.11;0.4.9-SNAPSHOT!ammonite-shell_2.11.jar:

	  /Users/pgiarrusso/.ivy2/cache/com.lihaoyi/ammonite-shell_2.11/jars/ammonite-shell_2.11-0.4.9-SNAPSHOT.jar

	==== local: tried

	  /Users/pgiarrusso/.ivy2/local/com.lihaoyi/ammonite-shell_2.11/0.4.9-SNAPSHOT/jars/ivy.xml

	  -- artifact com.lihaoyi#ammonite-shell_2.11;0.4.9-SNAPSHOT!ammonite-shell_2.11.jar:

	  /Users/pgiarrusso/.ivy2/local/com.lihaoyi/ammonite-shell_2.11/0.4.9-SNAPSHOT/jars/ammonite-shell_2.11.jar

	==== m2: tried

	  /Users/pgiarrusso/.m2/repository/com/lihaoyi/ammonite-shell_2.11/0.4.9-SNAPSHOT/ivy-0.4.9-SNAPSHOT.xml

	  -- artifact com.lihaoyi#ammonite-shell_2.11;0.4.9-SNAPSHOT!ammonite-shell_2.11.jar:

	  /Users/pgiarrusso/.m2/repository/com/lihaoyi/ammonite-shell_2.11/0.4.9-SNAPSHOT/ammonite-shell_2.11-0.4.9-SNAPSHOT.jar

	==== central: tried

	  http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.11/0.4.9-SNAPSHOT/ammonite-shell_2.11-0.4.9-SNAPSHOT.pom

	  -- artifact com.lihaoyi#ammonite-shell_2.11;0.4.9-SNAPSHOT!ammonite-shell_2.11.jar:

	  http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.11/0.4.9-SNAPSHOT/ammonite-shell_2.11-0.4.9-SNAPSHOT.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[error] (run-main-0) java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$evalMain(Evaluator.scala:125)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:247)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:244)
	at ammonite.repl.Res$Success.map(Util.scala:27)
	at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:244)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:149)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:135)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:352)
	at ammonite.repl.Repl.<init>(Repl.scala:28)
	at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:187)
	at ammonite.repl.Repl$.repl$1(Repl.scala:187)
	at ammonite.repl.Repl$.run(Repl.scala:195)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
Caused by: java.lang.ExceptionInInitializerError
	at cachec9d5e403e4daa42900277b14ba55878b.$main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$evalMain(Evaluator.scala:125)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:247)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:244)
	at ammonite.repl.Res$Success.map(Util.scala:27)
	at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:244)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:149)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:135)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:352)
	at ammonite.repl.Repl.<init>(Repl.scala:28)
	at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:187)
	at ammonite.repl.Repl$.repl$1(Repl.scala:187)
	at ammonite.repl.Repl$.run(Repl.scala:195)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
Caused by: ammonite.repl.IvyThing$IvyResolutionException: failed to resolve ivy dependencies unresolved dependency: com.lihaoyi#ammonite-shell_2.11;0.4.9-SNAPSHOT: not found
	at ammonite.repl.IvyThing$.resolveArtifact(IvyThing.scala:168)
	at ammonite.repl.interp.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:196)
	at cachec9d5e403e4daa42900277b14ba55878b$$anonfun$1.apply$mcV$sp(Main.scala:40)
	at cachec9d5e403e4daa42900277b14ba55878b$.<init>(Main.scala:41)
	at cachec9d5e403e4daa42900277b14ba55878b$.<clinit>(Main.scala)
	at cachec9d5e403e4daa42900277b14ba55878b.$main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$evalMain(Evaluator.scala:125)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:247)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:244)
	at ammonite.repl.Res$Success.map(Util.scala:27)
	at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:244)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:149)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:135)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:98)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:352)
	at ammonite.repl.Repl.<init>(Repl.scala:28)
	at ammonite.repl.Repl$.repl$lzycompute$1(Repl.scala:187)
	at ammonite.repl.Repl$.repl$1(Repl.scala:187)
	at ammonite.repl.Repl$.run(Repl.scala:195)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last repl/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last repl/compile:run for the full output.
[error] (repl/compile:run) Nonzero exit code: 1
[error] Total time: 48 s, completed Nov 9, 2015 4:42:40 PM
1. Waiting for source changes... (press enter to interrupt)
```

**Comment by lihaoyi** [comment]
This is probably due to the presence of 

```scala
load.ivy("com.lihaoyi" %% "ammonite-shell" % ammonite.Constants.version)
```

in your `~/.ammonite/predef.scala`. I need to find a way to make it more robust somehow, maybe when run in dev mode use the repo's predef by default unless otherwise specified?

**Comment by lihaoyi** [comment]
Try 
```
sbt "~repl/run --home=.ammonite-dev"
```

That should work and avoid mixing up your dev predef/cache/etc. with your "real" predef/cache/etc.

I'll update the readme

**Comment by Blaisorblade** [comment]
Correct diagnosis, thanks (I should have figured, I had forgot)!
But you should fix the README: you want a space instead of the `=`, so `sbt "~repl/run --home .ammonite-dev"` (just confirmed on latest master), so you might want to fix the readme for that.

Otherwise:

```
$ sbt "~repl/run --home=.ammonite-dev"
[info] Loading global plugins from /Users/pgiarrusso/.sbt/0.13/plugins
[info] Loading project definition from /Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/project
[info] Set current project to ammonite-tatooine (in build file:/Users/pgiarrusso/AeroFS/Repos/Ammonite-tatooine/)
[info] Running ammonite.repl.Repl --home=.ammonite-dev
Error: Unknown option --home=.ammonite-dev
ammonite 0.4.9-SNAPSHOT
Usage: ammonite [options] [<file>...]

  -p <value> | --predef <value>
        Any commands you want to execute at the start of the REPL session
  -f <value> | --predef-file <value>
        Lets you load your predef from a cuctom location
  -c <value> | --code <value>
        Pass in code to be run immediately in the REPL
  -h <file> | --home <file>
        The home directory of the REPL; where it looks for config and caches
  <file>...
        The Ammonite script file you want to execute
[success] Total time: 1 s, completed Nov 16, 2015 11:56:13 AM
```

OTOH, also accepting `=` might be nice for people mixing them up, like (ironically) you — the choice is arbitrary, different programs use different choices, and having to keep straight which programs use which conventions is mean.
