### ISSUE TITLE
Ammonite-Shell fail to run shell command on Mac OSX with gun coreutils installed

### ISSUE THREAD

**Issue by wuhx** [lihaoyi/Ammonite#259]
```
wuhx@gynoid:λ ./amm
Loading...
Welcome to the Ammonite Repl 0.4.8
(Scala 2.11.7 Java 1.8.0_11)
wuhx-sc@ wd
stty: standard input: unable to perform all requested operations
Exception in thread "main" java.lang.RuntimeException: Nonzero exit value: 1
	at scala.sys.package$.error(package.scala:27)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
	at ammonite.terminal.TTY$.stty(Utils.scala:78)
	at ammonite.terminal.TermCore$.readLine(TermCore.scala:240)
	at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:114)
	at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:25)
	at ammonite.repl.Repl.action(Repl.scala:45)
	at ammonite.repl.Repl.loop$1(Repl.scala:78)
	at ammonite.repl.Repl.run(Repl.scala:96)
	at ammonite.repl.Repl$.run(Repl.scala:195)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
```

when I remove gnu coreutils from PATH env， It works fine。
so it seems to have some incompatible issue with gnu coreutils (installed by brew) on osx.

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/Ammonite/pull/269
