### ISSUE TITLE
Tests fail to compile due to cached object

### ISSUE THREAD

**Issue by ssanj** [lihaoyi/Ammonite#261]
When running the tests I was getting a compilation error:

```
Exception in thread "main" ammonite.repl.CompilationError: Compilation Failed
Main.scala:36: not found: object cachec0e8d0fb27bf4efdde649d74df070d02
import cachec0e8d0fb27bf4efdde649d74df070d02.toString
       ^
    at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:152)
    at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:135)
    at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:98)
    at ammonite.repl.interp.Interpreter$$anon$1$load$.module(Interpreter.scala:234)
    at ammonite.repl.Repl$.run(Repl.scala:197)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
    at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
    at scala.Option.foreach(Option.scala:257)
    at ammonite.repl.Repl$.main(Repl.scala:158)
    at ammonite.repl.Repl.main(Repl.scala)
```

This was preventing me from running the tests in anyway. I tried an 

```
sbt clean
```
and reran the tests, but no luck. 

I stumbled across the ~/.ammonite/cache directory which had the referenced cache object
```
cachec0e8d0fb27bf4efdde649d74df070d02
```

I deleted this directory and then reran the tests. All the tests compiled as per usual. :)

I thought I'd document it here in case someone else ran across the same problem.

**Comment by lihaoyi** [comment]
I've run into this too. I somehow managed to go away in https://github.com/lihaoyi/Ammonite/commit/1f26e506aebe838102a30b67991dfc921314491d, but I do not understand it at all. 

It would be great if someone could figure it out =D

**Comment by lihaoyi** [comment]
This should be fixed by https://github.com/lihaoyi/Ammonite/commit/df48958efdecb1fe58a317b71dbcee06eb380505 I think, which properly invalidates all the caches when the execution classpath changes. Feel free to re-open if it's still happening in master
