### ISSUE TITLE
Compilation fails on Scalatex error

### ISSUE THREAD

**Issue by ssanj** [lihaoyi/Ammonite#270]
When running test:compile I get the following error:

```
[error] /Volumes/Work/projects/code/scala/opensource/Ammonite/readme/target/scala-2.11/src_managed/main/scalatex/Repl.scala:7: exception during macro expansion:
[error] java.lang.Exception: File:0 / Body:0 / BodyEx:0 / BodyItem:0 / SpecialIndented:1 / HeaderBlock:1 / Body:246 / BodyEx:246 / BodyItem:246 / SpecialIndented:248 / IndentScalaChain:248 / Body:296 / BodyEx:296 / BodyItem:2415 / SpecialIndented:2419 / IndentScalaChain:2419 / Body:2433 / BodyEx:2433 / BodyItem:5298 / SpecialIndented:5304 / IndentScalaChain:5304 / Body:5314 / BodyEx:5314 / BodyItem:5813 / SpecialIndented:5821 / IndentScalaChain:5821 / Body:5829 / BodyEx:5829 / BodyItem:5829 / SpecialIndented:5839 / HeaderBlock:5839 / Body:5861 / BodyEx:5861 / BodyItem:5892 / SpecialIndented:5902 / (IndentForLoop | IndentScalaChain | IndentIfElse | HeaderBlock | @@):5902 ..." sess.save"
[error] 	at scalatex.stages.Parser$.apply(Parser.scala:19)
[error] 	at scalatex.stages.Parser$.apply(Parser.scala:15)
[error] 	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:48)
[error] 	at scala.Function2$$anonfun$tupled$1.apply(Function2.scala:47)
[error] 	at scalatex.package$Internals$.compile$1(package.scala:83)
[error] 	at scalatex.package$Internals$.compileThing(package.scala:88)
[error] 	at scalatex.package$Internals$.applyMacroFileBase(package.scala:42)
[error] 	at scalatex.package$Internals$.applyMacroFile(package.scala:25)
[error]   def apply(): Frag = _root_.scalatex.twf("/Volumes/Work/projects/code/scala/opensource/Ammonite/readme/Repl.scalatex")
[error]
```

**Comment by lihaoyi** [comment]
yeah it's borked. I've been working on a fix in the `test` branch which just merged, should be working now i think
