### ISSUE TITLE
Ammonite-REPL 0.5.0 dies under Cygwin

### ISSUE THREAD

**Issue by mslinn** [lihaoyi/Ammonite#279]
I added the following to `~/.sbt/0.13/global.sbt`:

````
libraryDependencies += "com.lihaoyi" % "ammonite-repl" % "0.5.0" % "test" cross CrossVersion.full

initialCommands in (Test, console) := """ammonite.repl.Repl.run("")"""
````
Here is the error:

````
$ sbt test:console
[info] Loading global plugins from C:\Users\mslinn\.sbt\0.13\plugins
[info] Loading project definition from C:\work\courseNotes\project
[info] Set current project to Course (in build file:/C:/work/courseNotes/)
[info] Compiling 4 Scala sources to C:\work\courseNotes\target\scala-2.11\test-classes...
[info] Starting scala interpreter...
[info]
Loading...
Welcome to the Ammonite Repl 0.5.0
(Scala 2.11.6 Java 1.8.0_51)
bash: /dev/tty: No such device or address
bash: /dev/tty: No such device or address
java.lang.RuntimeException: Nonzero exit value: 1
  at scala.sys.package$.error(package.scala:27)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
  at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
  at ammonite.terminal.TTY$.stty(Utils.scala:85)
  at ammonite.terminal.TTY$.init(Utils.scala:64)
  at ammonite.terminal.TermCore$.x$6$lzycompute$1(TermCore.scala:242)
  at ammonite.terminal.TermCore$.x$6$1(TermCore.scala:242)
  at ammonite.terminal.TermCore$.initialConfig$lzycompute$1(TermCore.scala:242)
  at ammonite.terminal.TermCore$.initialConfig$1(TermCore.scala:242)
  at ammonite.terminal.TermCore$.readLine(TermCore.scala:252)
  at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:110)
  at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:25)
  at ammonite.repl.Repl.action(Repl.scala:45)
  at ammonite.repl.Repl.loop$1(Repl.scala:78)
  at ammonite.repl.Repl.run(Repl.scala:96)
  at ammonite.repl.Repl$.run(Repl.scala:195)
  ... 39 elided
Welcome to Scala version 2.11.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_51).
Type in expressions to have them evaluated.
Type :help for more information.
````

The above works fine under XUbuntu.

**Comment by djx314** [comment]
#119
```scala
{
  if (org.xarcher.sbt.OSName.isWindows)
    initialCommands in (Test, console) += s"""ammonite.repl.Repl.run("repl.frontEnd() = ammonite.repl.frontend.FrontEnd.JLineWindows");"""
  else if (org.xarcher.sbt.OSName.isLinux)
    initialCommands in (Test, console) += s"""ammonite.repl.Repl.run("");"""
  else
    initialCommands in (Test, console) += s""""""
}
```

org.xarcher.sbt.OSName.isWindows is a method to judgment the os.
Hope for any way to support tty in cygwin.

**Comment by lihaoyi** [comment]
Closing as duplicate; let's focus the discussion over at https://github.com/lihaoyi/Ammonite/issues/119. I don't have a windows machine right now to get this working, but I'd love if someone could take a crack at this.

@djx314 want to re-post your workaround under that issue?
