### ISSUE TITLE
Ammonite REPL confused by singleton types

### ISSUE THREAD

**Issue by tpolecat** [lihaoyi/Ammonite#280]
Ammonite seems confused by shapeless's ability to conjure up singleton types, which makes extensible records and other things not work.

```scala
@ shapeless.Witness(1)
Compilation Failed
Main.scala:46: exception during macro expansion: 
scala.MatchError: Int(1) (of class scala.reflect.internal.Types$UniqueConstantType)
	at ammonite.repl.frontend.TPrintLowPri$.rec0$1(TPrintImpl.scala:144)
	at ammonite.repl.frontend.TPrintLowPri$.typePrintImpl(TPrintImpl.scala:181)

              .print(res0, res0, "res0", scala.None)
                    ^
```

**Comment by lihaoyi** [comment]
I cannot reproduce this either on master or on the last published version 0.5.2
```scala
haoyi-mbp:Ammonite haoyi$ sbt repl/test:run
[info] Loading global plugins from /Users/haoyi/.sbt/0.13/plugins
[info] Loading project definition from /Users/haoyi/Dropbox (Personal)/Workspace/Ammonite/project
[info] Set current project to ammonite (in build file:/Users/haoyi/Dropbox%20(Personal)/Workspace/Ammonite/)
[info] Running ammonite.repl.TestMain
Loading...
Welcome to the Ammonite Repl 0.5.3-SNAPSHOT
(Scala 2.11.7 Java 1.8.0_25)
@ load.ivy(
@ load.ivy("com.chuusai" %% "shapeless" % "2.1.0")
:: loading settings :: url = jar:file:/Users/haoyi/.ivy2/cache/org.apache.ivy/ivy/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: com.chuusai#shapeless_2.11-caller;working
	confs: [default]
	found com.chuusai#shapeless_2.11;2.1.0 in chain-resolver
	found org.scala-lang#scala-library;2.11.5 in chain-resolver
	found org.scala-lang#scala-compiler;2.11.5 in central
	found org.scala-lang#scala-reflect;2.11.5 in chain-resolver
	found org.scala-lang.modules#scala-xml_2.11;1.0.3 in chain-resolver
	found org.scala-lang.modules#scala-parser-combinators_2.11;1.0.3 in chain-resolver

:: problems summary ::
:::: ERRORS
	unknown resolver sbt-chain

	unknown resolver sbt-chain

	unknown resolver sbt-chain

	unknown resolver sbt-chain

	unknown resolver sbt-chain


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS

@ shapeless.Witness(1)
res1: AnyRef with shapeless.Witness{type T = Int(1)} = cmd1$fresh$macro$1$1@78f3e63b
@ Bye!
[success] Total time: 54 s, completed Jan 30, 2016 4:46:56 PM
haoyi-mbp:Ammonite haoyi$ ~/amm
Loading...
Welcome to the Ammonite Repl 0.5.2
(Scala 2.11.7 Java 1.8.0_25)
haoyi-Ammonite@ load.ivy("com.chuusai" %% "shapeless" % "2.1.0")
:: loading settings :: url = jar:file:/Users/haoyi/amm!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: com.chuusai#shapeless_2.11-caller;working
	confs: [default]
	found com.chuusai#shapeless_2.11;2.1.0 in chain-resolver
	found org.scala-lang#scala-library;2.11.5 in chain-resolver
	found org.scala-lang#scala-compiler;2.11.5 in central
	found org.scala-lang#scala-reflect;2.11.5 in chain-resolver
	found org.scala-lang.modules#scala-xml_2.11;1.0.3 in chain-resolver
	found org.scala-lang.modules#scala-parser-combinators_2.11;1.0.3 in chain-resolver

haoyi-Ammonite@ shapeless.Witness(1)
res1: AnyRef with shapeless.Witness{type T = Int(1)} = cmd1$fresh$macro$1$1@3020f22
```

**Comment by lihaoyi** [comment]
Feel free to ping back if you have a solid repro

**Comment by alexarchambault** [comment]
Here it is:
```scala
Welcome to the Ammonite Repl 0.5.2
(Scala 2.11.7 Java 1.8.0_60)
@ load.ivy("com.chuusai" %% "shapeless" % "2.2.5")

@ import shapeless.syntax.singleton._
import shapeless.syntax.singleton._
@ 2.narrow
Compilation Failed
Main.scala:66: exception during macro expansion:
scala.MatchError: Int(2) (of class scala.reflect.internal.Types$UniqueConstantType)
	at ammonite.repl.frontend.TPrintLowPri$.rec0$1(TPrintImpl.scala:144)
	at ammonite.repl.frontend.TPrintLowPri$.typePrintImpl(TPrintImpl.scala:181)

              .print(res2, res2, "res2", scala.None)
                    ^
```
