### ISSUE TITLE
Error executing as script

### ISSUE THREAD

**Issue by gorzell** [lihaoyi/Ammonite#307]
I am trying to run an ammonite script as self contained unix script file.  Unfortunately it seems like ammonite is trying to interpret the initial execution lines rather than ignoring them.  Is this a bug, or is there some better way of doing this that I couldn't find in the docs?

Repro:
create hello.scala file and set it to executable.  Adding the following contents:
```scala
#!/bin/sh
  exec amm $0 $@
!#

println("hello")
```

./hello.scala gives the following error:
```
Exception in thread "main" ammonite.repl.CompilationError: Compilation Failed
Main.scala:39: not found: value exec
exec amm $0 $
^
Main.scala:39: not found: value $0
exec amm $0 $
         ^
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:149)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:132)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:95)
	at ammonite.repl.interp.Interpreter$$anon$1$load$.module(Interpreter.scala:231)
	at ammonite.repl.Repl$.run(Repl.scala:197)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:159)
	at ammonite.repl.Repl$$anonfun$main$1.apply(Repl.scala:158)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Repl$.main(Repl.scala:158)
	at ammonite.repl.Repl.main(Repl.scala)
```

I took most of this example from the docs (http://www.scala-lang.org/old/node/166.html) and if you use the scala command it works as expected.

**Comment by lihaoyi** [comment]
Ammonite only works with a single-line hash-bang header. Is there a way you can fit all that on one line?

**Comment by gorzell** [comment]
I will take a look, do you have an example of what you would normally put on the one line?

**Comment by lihaoyi** [comment]
I don't off the top of my head, but this should work maybe? https://github.com/lihaoyi/Ammonite/pull/210 I haven't used it actively so I don't actually know. The author of that PR probably knows

**Comment by lihaoyi** [comment]
I normally run all my scripts with `amm x.scala` `python x.py` etc. :stuck_out_tongue:

**Comment by gorzell** [comment]
This seems to be working for me...

`#!/usr/bin/env amm`

**Comment by lihaoyi** [comment]
Ok cool =)
