### ISSUE TITLE
Show proper script name and line numbers when script fails

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#321]
Current the error message for compile errors, parse errors, and runtime errors are all different, and variously unhelpful:

*Compile Error*
```scala
haoyi-mbp:~ haoyi$ vim script.scala
haoyi-mbp:~ haoyi$ cat script.scala
println(1)
@
println(*)
haoyi-mbp:~ haoyi$ ~/amm script.scala
1
Exception in thread "main" ammonite.repl.CompilationError: Compilation Failed
Main.scala:41: not found: value *
println(*)
        ^
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:151)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:162)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:97)
	at ammonite.repl.Main$.runScript(Main.scala:143)
	at ammonite.repl.Main$.run(Main.scala:136)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:82)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:81)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Main$.main(Main.scala:81)
	at ammonite.repl.Main.main(Main.scala)
```
*Parse Error*
```scala
haoyi-mbp:~ haoyi$ vim script.scala
haoyi-mbp:~ haoyi$ cat script.scala
println(1)
@
println(*
haoyi-mbp:~ haoyi$ ~/amm script.scala
Exception in thread "main" fastparse.core.ParseError: found "", expected "," | ")" at index 420

^
	at fastparse.core.Parsed$class.get(Parsing.scala:29)
	at fastparse.core.Parsed$Failure.get(Parsing.scala:84)
	at ammonite.repl.Parsers$.splitScript(Parsers.scala:47)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:121)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:97)
	at ammonite.repl.Main$.runScript(Main.scala:143)
	at ammonite.repl.Main$.run(Main.scala:136)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:82)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:81)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Main$.main(Main.scala:81)
	at ammonite.repl.Main.main(Main.scala)
```
*Runtime Error*: first run for some reason runs into cache problems, second run is the unhelpful error
```scala
haoyi-mbp:~ haoyi$ vim script.scala
haoyi-mbp:~ haoyi$ cat script.scala
println(1)
@
println(???)
haoyi-mbp:~ haoyi$ ~/amm script.scala
1
Exception in thread "main" ammonite.repl.CompilationError: Compilation Failed
Main.scala:37: not found: object cache7bf639cce6ffabf144e303440d3ed1d0
import cache7bf639cce6ffabf144e303440d3ed1d0.res
       ^
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:151)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:162)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:97)
	at ammonite.repl.Main$.runScript(Main.scala:143)
	at ammonite.repl.Main$.run(Main.scala:136)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:82)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:81)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Main$.main(Main.scala:81)
	at ammonite.repl.Main.main(Main.scala)
haoyi-mbp:~ haoyi$ rm -rf ~/.ammonite/cache/
haoyi-mbp:~ haoyi$ ~/amm script.scala
1
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$evalMain(Evaluator.scala:160)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:282)
	at ammonite.repl.interp.Evaluator$$anon$1$$anonfun$processScriptBlock$2.apply(Evaluator.scala:279)
	at ammonite.repl.Res$Success.map(Util.scala:29)
	at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:279)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:97)
	at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:97)
	at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:148)
	at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:162)
	at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:97)
	at ammonite.repl.Main$.runScript(Main.scala:143)
	at ammonite.repl.Main$.run(Main.scala:136)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:82)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:81)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Main$.main(Main.scala:81)
	at ammonite.repl.Main.main(Main.scala)
Caused by: scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at cache697d06a49aa6a4fe90d79ce9a0b07563$.<init>(Main.scala:41)
	at cache697d06a49aa6a4fe90d79ce9a0b07563$.<clinit>(Main.scala)
	at cache697d06a49aa6a4fe90d79ce9a0b07563.$main(Main.scala)
	... 21 more
```

- They should all show, at the very least, the name of the script that failed. 
- Ideally they would also show the correct line number.
- The parse error should show the line/column, rather than just the index
- The `InvocationTargetException` wrapping the runtime error should also be stripped; it's unhelpful.

**Comment by lihaoyi** [comment]
@coderabhishek has fixed this.

Thanks @coderabhishek !
