### ISSUE TITLE
Exception during macro expansion: value MINUTES is not a type

### ISSUE THREAD

**Issue by stanch** [lihaoyi/Ammonite#329]
```scala
Loading...
Welcome to the Ammonite Repl 0.4.5
(Scala version 2.11.7 Java 1.8.0_45)
@ import scala.concurrent.duration.DurationInt
import scala.concurrent.duration.DurationInt
@ 2 days
Compilation Failed
Main.scala:53: exception during macro expansion: 
scala.ScalaReflectionException: value MINUTES is not a type
	at scala.reflect.api.Symbols$SymbolApi$class.asType(Symbols.scala:183)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asType(Symbols.scala:84)
	at derive.Derive$$anonfun$impl$1$2.apply(Derive.scala:75)
	at derive.Derive$$anonfun$impl$1$2.apply(Derive.scala:74)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
	at scala.collection.SetLike$class.map(SetLike.scala:92)
	at scala.collection.AbstractSet.map(Set.scala:47)
	at derive.Derive.impl$1(Derive.scala:74)
	at derive.Derive.fleshedOutSubtypes(Derive.scala:81)
	at derive.Derive.derive$Derive$$onFail$1(Derive.scala:136)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:204)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:178)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at derive.Derive.derive$Derive$$rec$1(Derive.scala:178)
	at derive.Derive$$anonfun$5.apply(Derive.scala:157)
	at derive.Derive$$anonfun$5.apply(Derive.scala:157)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at derive.Derive.derive$Derive$$onFail$1(Derive.scala:157)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:204)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:178)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at derive.Derive.derive$Derive$$rec$1(Derive.scala:178)
	at derive.Derive.deriveType(Derive.scala:217)
	at derive.Derive.derive(Derive.scala:58)
	at pprint.Internals$LowerPriPPrint$.liftedTree1$1(PPrint.scala:398)
	at pprint.Internals$LowerPriPPrint$.FinalRepr(PPrint.scala:398)

        def $main() = { ammonite.repl.frontend.ReplBridge.repl.Internal.combinePrints(ammonite.repl.frontend.ReplBridge.repl.Internal.print(res1, res1, "res1", None)) }
                                                                                                                                           ^
```

**Comment by lihaoyi** [comment]
Seems to work in 0.5.2?

```scala
Welcome to the Ammonite Repl 0.5.2
(Scala 2.11.7 Java 1.8.0_25)
@ import scala.concurrent.duration.DurationInt
import scala.concurrent.duration.DurationInt
@ 2 days
res1: concurrent.duration.FiniteDuration = 2 days
```

**Comment by stanch** [comment]
Nice, gonna update :)
