### ISSUE TITLE
breaks when creating a shapeless coproduct

### ISSUE THREAD

**Issue by caente** [lihaoyi/Ammonite#333]
I'd be more than happy to send a PR to fix this, but I'd appreciate any hit as to where to start
```
@ import shapeless._
import shapeless._
@ type C = Int :+: String :+: CNil
defined type C
@ Coproduct[C](1)
Compilation Failed
Main.scala:283: exception during macro expansion:
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.subst(TypeMaps.scala:709)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.substFor$1(TypeMaps.scala:717)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:732)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:685)
	at scala.collection.immutable.List.loop$1(List.scala:173)
	at scala.collection.immutable.List.mapConserve(List.scala:189)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:115)
	at scala.reflect.internal.tpe.TypeMaps$SubstMap.apply(TypeMaps.scala:716)
	at scala.reflect.internal.Types$Type.subst(Types.scala:705)
	at scala.reflect.internal.Types$TypeApiImpl.substituteTypes(Types.scala:240)
	at scala.reflect.internal.Types$TypeApiImpl.substituteTypes(Types.scala:218)
	at derive.Derive$$anonfun$impl$1$3.apply(Derive.scala:80)
	at derive.Derive$$anonfun$impl$1$3.apply(Derive.scala:75)
	at scala.collection.TraversableLike$WithFilter$$anonfun$map$2.apply(TraversableLike.scala:728)
	at scala.collection.immutable.Set$Set2.foreach(Set.scala:111)
	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
	at derive.Derive.impl$1(Derive.scala:75)
	at derive.Derive.fleshedOutSubtypes(Derive.scala:84)
	at derive.Derive.derive$Derive$$onFail$1(Derive.scala:139)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:207)
	at derive.Derive$$anonfun$derive$Derive$$rec$1$1.apply(Derive.scala:181)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:194)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
	at derive.Derive.derive$Derive$$rec$1(Derive.scala:181)
	at derive.Derive.deriveType(Derive.scala:220)
	at derive.Derive.derive(Derive.scala:58)
	at pprint.Internals$LowerPriPPrint$.liftedTree1$1(PPrint.scala:398)
	at pprint.Internals$LowerPriPPrint$.FinalRepr(PPrint.scala:398)

              .print(res2, res2, "res2", scala.None)
                    ^
```

**Comment by caente** [comment]
it works fine for hlists though

**Comment by lihaoyi** [comment]
Duplicate https://github.com/lihaoyi/Ammonite/issues/198

**Comment by lihaoyi** [comment]
If you want to fix this, look at the part of the stack trace in `Derive.scala` where it's blowing up, and stop it :smile:
