### ISSUE TITLE
Can't run ammonite in windows

### ISSUE THREAD

**Issue by ittayd** [lihaoyi/Ammonite#340]
Welcome to the Ammonite Repl 0.5.5-SNAPSHOT
(Scala 2.11.7 Java 1.8.0_40)
"bash": stty: command not found
"bash": stty: command not found
[error] (run-main-3) java.lang.RuntimeException: Nonzero exit value: 127
java.lang.RuntimeException: Nonzero exit value: 127
        at scala.sys.package$.error(package.scala:27)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:132)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:102)
        at ammonite.terminal.TTY$.stty(Utils.scala:90)
        at ammonite.terminal.TTY$.init(Utils.scala:69)
        at ammonite.terminal.TermCore$.x$6$lzycompute$1(TermCore.scala:252)
        at ammonite.terminal.TermCore$.x$6$1(TermCore.scala:252)
        at ammonite.terminal.TermCore$.initialConfig$lzycompute$1(TermCore.scala:252)
        at ammonite.terminal.TermCore$.initialConfig$1(TermCore.scala:252)
        at ammonite.terminal.TermCore$.readLine(TermCore.scala:262)
        at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:112)
        at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:25)
        at ammonite.repl.Repl.action(Repl.scala:55)
        at ammonite.repl.Repl.loop$1(Repl.scala:88)
        at ammonite.repl.Repl.run(Repl.scala:106)
        at ammonite.repl.Main$.run(Main.scala:135)
        at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:82)
        at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:81)
        at scala.Option.foreach(Option.scala:257)
        at ammonite.repl.Main$.main(Main.scala:81)
        at ammonite.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last repl/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1

**Comment by lihaoyi** [comment]
Duplicate https://github.com/lihaoyi/Ammonite/issues/119
