### ISSUE TITLE
Unusual behaviour of Ammonite history search

### ISSUE THREAD

**Issue by coderabhishek** [lihaoyi/Ammonite#366]
While trying to auto-complete an import statement by searching in history (up key),I encountered following unusual behavior :
`
abhishek@abhishek-Inspiron-3542:~$ ~/amm
Loading...
Welcome to the Ammonite Repl 0.5.5
(Scala 2.11.7 Java 1.8.0_66-internal)

abhishek-abhishek@ import scala.tools.reflect.ToolBox
` 

import statement loaded from history,if once more "up" key is pressed,Ammonite crashes as follows:

`
abhishek@abhishek-Inspiron-3542:~$ ~/amm
Loading...
Welcome to the Ammonite Repl 0.5.5
(Scala 2.11.7 Java 1.8.0_66-internal)

abhishek-abhishek@ import scala.tools.reflect.ToolBoxException in thread "main" java.util.NoSuchElementException: key not found: :q
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at ammonite.terminal.Ansi$Str$$anonfun$parse$3.apply(Ansi.scala:133)
	at ammonite.terminal.Ansi$Str$$anonfun$parse$3.apply(Ansi.scala:129)
	at scala.collection.immutable.Stream$StreamWithFilter.foreach(Stream.scala:570)
	at ammonite.terminal.Ansi$Str$.parse(Ansi.scala:129)
	at ammonite.repl.frontend.AmmoniteFrontEnd$$anonfun$6.apply(AmmoniteFrontEnd.scala:130)
	at ammonite.repl.frontend.AmmoniteFrontEnd$$anonfun$6.apply(AmmoniteFrontEnd.scala:119)
	at ammonite.terminal.TermCore$.x$3$lzycompute$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.x$3$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.transformedBuffer0$lzycompute$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.transformedBuffer0$1(TermCore.scala:222)
	at ammonite.terminal.TermCore$.readChar$1(TermCore.scala:227)
	at ammonite.terminal.TermCore$.readLine(TermCore.scala:299)
	at ammonite.repl.frontend.AmmoniteFrontEnd.readLine(AmmoniteFrontEnd.scala:114)
	at ammonite.repl.frontend.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:26)
	at ammonite.repl.Repl.action(Repl.scala:56)
	at ammonite.repl.Repl.loop$1(Repl.scala:89)
	at ammonite.repl.Repl.run(Repl.scala:107)
	at ammonite.repl.Main$.run(Main.scala:135)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:82)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:81)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Main$.main(Main.scala:81)
	at ammonite.repl.Main.main(Main.scala)
abhishek@abhishek-Inspiron-3542:~$ 
`

**Comment by lihaoyi** [comment]
@coderabhishek can you minimize?

**Comment by lihaoyi** [comment]
Could you also use `Ctrl Q` to drop into echo-characters mode, and see what character codes your UP key prints out

**Comment by coderabhishek** [comment]
Surprisingly I am unable to reproduce this bug! Maybe it was some random terminal issue but I've encountered it many times previously.It seems to be due to some random reason.

**Comment by coderabhishek** [comment]
Sometimes pressing arrow keys deletes what was printed above in Ammonite terminal,but sadly I don't know how to reproduce it.

**Comment by lihaoyi** [comment]
Ok well i'll close this for now, if you want to discuss this further let's do it in the public gitter channel and I can try to help debug and walk you through possible repros. If we find something reliable we can re-open this!
