### ISSUE TITLE
NullPointerException in 0.5.7

### ISSUE THREAD

**Issue by cvogt** [lihaoyi/Ammonite#368]
Trying to invoke `ammonite.repl.Main` from an application via reflection leads to this for me. Ammonite is not on the general classpath, but loaded via an URLClassLoader here.

```
Caused by: java.lang.NullPointerException
	at ammonite.ops.Readable$class.getBytes(Path.scala:46)
	at ammonite.ops.Readable$InputStreamToReadable.getBytes(Path.scala:63)
	at ammonite.ops.read$bytes$.apply(FileOps.scala:315)
	at ammonite.repl.interp.SpecialClassLoader.ammonite$repl$interp$SpecialClassLoader$$special$1(ClassLoaders.scala:139)
	at ammonite.repl.interp.SpecialClassLoader$$anonfun$findClass$2.apply(ClassLoaders.scala:148)
	at ammonite.repl.interp.SpecialClassLoader$$anonfun$findClass$2.apply(ClassLoaders.scala:148)
	at scala.Option.orElse(Option.scala:289)
	at ammonite.repl.interp.SpecialClassLoader.findClass(ClassLoaders.scala:148)
	at ammonite.repl.interp.SpecialClassLoader.findClassPublic(ClassLoaders.scala:124)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:374)
	at ammonite.repl.Repl.<init>(Repl.scala:38)
	at ammonite.repl.Main$.repl$lzycompute$1(Main.scala:130)
	at ammonite.repl.Main$.repl$1(Main.scala:130)
	at ammonite.repl.Main$.run(Main.scala:136)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:87)
	at ammonite.repl.Main$$anonfun$main$2.apply(Main.scala:85)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.repl.Main$.main(Main.scala:85)
	at ammonite.repl.Main.main(Main.scala)
```

**Comment by lihaoyi** [comment]
come to the gitter channel when you're free and let's try debugging this together

**Comment by lihaoyi** [comment]
closing due to inactivity
