### ISSUE TITLE
"java.io.IOException: Class not found" is thrown with Spark partitions

### ISSUE THREAD

**Issue by brendanmaguire** [lihaoyi/Ammonite#382]
When running the following script:

``` scala
import org.apache.spark.{SparkContext, SparkConf}
import org.apache.spark.sql.SQLContext

val conf = new SparkConf().setMaster("local[*]").setAppName("bxm")
val sc = new SparkContext(conf)
val sqlContext = new SQLContext(sc)

val df = sqlContext.read.json("data.json")

df.foreachPartition{records =>
  records.foreach(record => println("fake db write"))
}
```

I get this error:

```
java.io.IOException: Class not found
  org.apache.xbean.asm5.ClassReader.a(null:-1)
  org.apache.xbean.asm5.ClassReader.<init>(null:-1)
  org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:40)
  org.apache.spark.util.ClosureCleaner$.getInnerClosureClasses(ClosureCleaner.scala:81)
  org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:187)
  org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
  org.apache.spark.SparkContext.clean(SparkContext.scala:2055)
  org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:919)
  org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:918)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
  org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
  org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
  org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:918)
  org.apache.spark.sql.DataFrame$$anonfun$foreachPartition$1.apply$mcV$sp(DataFrame.scala:1483)
  org.apache.spark.sql.DataFrame$$anonfun$foreachPartition$1.apply(DataFrame.scala:1483)
  org.apache.spark.sql.DataFrame$$anonfun$foreachPartition$1.apply(DataFrame.scala:1483)
  org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
  org.apache.spark.sql.DataFrame.withNewExecutionId(DataFrame.scala:2125)
  org.apache.spark.sql.DataFrame.foreachPartition(DataFrame.scala:1482)
  cmd6$.<init>(Main.scala:142)
  cmd6$.<clinit>(Main.scala:-1)
```

I don't get this error when running within the standard repl.

I'm using the following versions of the spark libs:

```
"org.apache.spark" %% "spark-core" % "1.6.0",
"org.apache.spark" %% "spark-sql" % "1.6.0"
```

and ammonite 0.5.7.

Any ideas? Is this a known issue?

**Comment by lihaoyi** [comment]
I've never used spark before, my understanding is that it doesn't work. 

But we should make it work. I don't know anything about Spark. Can you provide a self-contained example with all relevant setup, data-files (e.g. what's `data.json`?) etc. included so I have something to work with? If you give me that I'm pretty confident I'll be able to make it work...

**Comment by brendanmaguire** [comment]
Cheers! I have created a repo [here](https://github.com/brendanmaguire/ammonite-spark-bug) which you can use to reproduce the bug.

**Comment by JohnReedLOL** [comment]
@lihaoyi - [Spark](http://spark.apache.org/) has it's own Scala REPL called Spark Shell. Spark is used for distributed parallel computing (MapReduce, Hadoop File System). The spark REPL is based on the standard Scala REPL, but I would like Ammonite shell to be able to be used. https://github.com/apache/spark

**Comment by jvimal** [comment]
@lihaoyi in short, the issue here is that ammonite's compiled class bytecode is inaccessible from the ammonite shell's classloader.

Long version:

Spark shell uses the standard `scala.tools.nsc.Interpreter` way to instantiate the shell, and uses ClosureCleaner to serialise closures.

The way spark does this is by:
- Getting the name of the anonymous class `cls` using `cls.getName` and tweaking it
- Getting the class byte code using `cls.getResourceAsStream(tweakedName + ".class")`

When I set a breakpoint in ClosureCleaner.getClassReader, I see that the anonymous class (containing the `records => ...` closure in the issue comment (https://github.com/lihaoyi/Ammonite/issues/382#issue-151843542) is unable to fetch its own resource when using ammonite shell, but it works fine with scala's standalone `nsc.Interpreter` shell.

**Comment by jvimal** [comment]
I was able to solve this issue.  Turns out there're a few steps to do, as the root-cause is also due to a peculiarity of Spark.

1. Change Ammonite's SpecialClassLoader to override URLCLassLoader's `getResourceAsStream(name)` so it returns the anonymous, REPL-defined closures.  Spark uses this in its ClosureSerializer.  While this step solves the task serialization problem (i.e., `rdd.map(x => x+1)` will now compile properly), it does not execute, because the spark executor does not have access to the `x => x+1` closure defined in the REPL.  This leads us to step (2):

2. Change Ammonite to save the class bytecodes in `SpecialClassLoader.newFileDict` to a disk at a temporary directory, and serve this directory using a HttpServer.

3. Set Spark's `spark.repl.class.uri` setting when initialising `SparkConf` (this setting has changed across Spark versions) to point to the HTTP server's URI.

Steps (2) and (3) ensure that once spark serialises the tasks and sends them to executors, the executor can also load these REPL-defined classes using its URLClassLoader.  This is exactly what Spark does in spark-repl package.

I think (1) and (2) are a useful change to Ammonite, so I can send a PR if you feel it's a nice to have.  Step (3) is very specific to Spark, so I can send out a gist so others can benefit from it.

**Comment by alexarchambault** [comment]
FYI, that's the kind of things I did here: https://github.com/alexarchambault/ammonium

**Comment by jvimal** [comment]
@alexarchambault Thanks for the link!  I did take a look at it.  Do you have some examples on how I can initiate the Repl just like Ammonite?  i.e., I just want to drop this into my code:

```scala
    ammonite.repl.Main.run()
```

Is it possible to do this in Ammonium?  A gist example would be great.

**Comment by alexarchambault** [comment]
Something like
- depend on `"com.github.alexarchambault.ammonium" % "shell" % "0.4.0-M6" cross CrossVersion.full`,
- call `ammonite.Ammonite.main(Array())`,
should do the job.

If you plan to use some of the code around from the shell / jobs run from it, there should be some extra things to do though.

**Comment by alexarchambault** [comment]
Plus follow https://github.com/alexarchambault/ammonium#spark to setup spark from the shell.

**Comment by lihaoyi** [comment]
Feel free to send a PR jvimal!

alexarchambault I wouldn't mind a PR from you either (on this or other
topics), if you promise to be patient with me understanding and merging it
=P

**Comment by alexarchambault** [comment]
I can try if time allows. Some of the changes were quite wide-ranging though... hence my hesitation (plus I wasn't really knowing what I was doing when I initially wrote them :-), so that made them a bit hard to explain / justify).

**Comment by alexarchambault** [comment]
What @jvimal proposes is a first step in the right direction, some extra work was needed too (I could have a look at it another time).

**Comment by dportabella** [comment]
is this issue solved?
I am using the latest amm version (0.7.6), and I still get the same error.
See this example https://github.com/lihaoyi/Ammonite/issues/463

**Comment by jvimal** [comment]
@dportabella nope.  This needs more work for integration tests, which I did not have time to do.  You can see #389 for more info and context.

**Comment by hbutani** [comment]
Here is a very light touch  integration: https://github.com/SparklineData/snapshell
Basically we replace Spark's ILoop with an Ammonite Repl, but let leave `spark.repl.Main` mostly in charge. Note, this comes from the perspective of snap-shell being a drop in replacement for spark-shell(all spark-submit options work).

**Comment by lihaoyi** [comment]
This seems to work as of https://github.com/lihaoyi/Ammonite/commit/662859f84f5a77efca3e7e4d3074626570a992cf, and has been added to the test suite:
```scala
import $ivy.{
  `org.apache.spark::spark-core:2.1.0`,
  `org.apache.spark::spark-sql:2.1.0`
}
import ammonite.ops._
import org.apache.spark.{SparkContext, SparkConf}
import org.apache.spark.sql.SQLContext

val conf = new SparkConf().setMaster("local[*]").setAppName("bxm")
val sc = new SparkContext(conf)
val sqlContext = new SQLContext(sc)

val df = sqlContext.read.json(
  "integration/src/test/resources/ammonite/integration/basic/Spark2.json"
)

df.foreachPartition{records =>
  records.foreach{
    record => println("fake db write")
  }
}
```

Notably, a small change makes it hang:

```scala
import $ivy.{
  `org.apache.spark::spark-core:2.1.0`,
  `org.apache.spark::spark-sql:2.1.0`
}
import ammonite.ops._
import org.apache.spark.{SparkContext, SparkConf}
import org.apache.spark.sql.SQLContext

val conf = new SparkConf().setMaster("local[*]").setAppName("bxm")
val sc = new SparkContext(conf)
val sqlContext = new SQLContext(sc)

val df = sqlContext.read.json(
  "integration/src/test/resources/ammonite/integration/basic/Spark2.json"
)

var i = 0
df.foreachPartition{records =>
  records.foreach{
    record => i += 1; println("fake db write " + i)
  }
}
```

It's not clear how/why that is hanging; any spark experts around?

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out

**Comment by timvw** [comment]
It is even possible to submit jobs via yarn..

```code
interp.load.cp(ammonite.ops.Path("/etc/hive/conf"))

import $ivy.{
        `org.apache.spark::spark-core:2.2.0`,
        `org.apache.spark::spark-sql:2.2.0`,
        `org.apache.spark::spark-yarn:2.2.0`
}
import org.apache.spark.{SparkContext, SparkConf}
import org.apache.spark.sql.SQLContext

val conf = new SparkConf().setMaster("yarn-client").setAppName("timvwamm")
val sc = new SparkContext(conf)
val sqlContext = new SQLContext(sc)
val rdd = sc.textFile("hdfs://nameservice1/blah/blah/part-0000.gz")
println(s"count is " +  rdd.count())

sc.stop()

```

**Comment by alexarchambault** [comment]
I published  [ammonite-spark](https://github.com/alexarchambault/ammonite-spark), which makes plenty of other spark things work (spark serializing stuff from the Ammonite session should work fine - when mapping on RDDs or defining UDFs, all the dependencies are passed to the spark session, etc.)

**Comment by Puli-Bharatharatna** [comment]
Hi everyone. I too am facing a similar issue. Were you guys able to solve this? If yes, can you please help me with the same?

Traceback (most recent call last):
  File "testcase1.py", line 46, in <module>
    print("Number of records: " + str(df_data.count()))
  File "/anaconda3/lib/python3.6/site-packages/pyspark/sql/dataframe.py", line 455, in count
    return int(self._jdf.count())
  File "/anaconda3/lib/python3.6/site-packages/py4j/java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/anaconda3/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/anaconda3/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o35.count.
: java.lang.IllegalArgumentException
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:46)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:449)
	at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:432)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:432)
	at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.b(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.xbean.asm5.ClassReader.accept(Unknown Source)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:262)
	at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:261)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:261)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2299)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2073)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2099)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:939)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:938)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:297)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2770)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2769)
	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3254)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3253)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2769)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:844)
