### ISSUE TITLE
$file import fails for scripts in nested folders if you leave out the `.sc` when running script

### ISSUE THREAD

**Issue by lihaoyi** [lihaoyi/Ammonite#417]
```scala
haoyi-mbp:~ haoyi$ amm A
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:646)
	at ammonite.util.Name.<init>(Model.scala:120)
	at ammonite.util.Util$.pathToPackageWrapper(Util.scala:23)
	at ammonite.main.Scripts$.runScript(Scripts.scala:20)
	at ammonite.Main.runScript(Main.scala:82)
	at ammonite.Main$$anonfun$main$1$$anonfun$apply$1.apply(Main.scala:193)
	at ammonite.Main$.ammonite$Main$$ifContinually$1(Main.scala:173)
	at ammonite.Main$$anonfun$main$1.apply(Main.scala:175)
	at ammonite.Main$$anonfun$main$1.apply(Main.scala:175)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.Main$.main(Main.scala:175)
	at ammonite.Main.main(Main.scala)
```

A file `A` doesn't need to exist, nor does `A.sc`. Nevertheless, we should fail with a better error message

**Comment by lihaoyi** [comment]
Fixed by #425
