### ISSUE TITLE
amm fails if ran from /var or /bin

### ISSUE THREAD

**Issue by 13h3r** [lihaoyi/Ammonite#418]
```
alexey@Alexeys-MacBook-Pro /var » cat > /Users/alexey/temp/C.sc                                                                    1 ↵
println("It works")
alexey@Alexeys-MacBook-Pro /var » amm /Users/alexey/temp/C.sc
It works
Exception in thread "main" java.lang.ClassNotFoundException: $file.`..`.`..`.Users.alexey.temp.C$$routes$
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at ammonite.interp.SpecialClassLoader.findClass(ClassLoaders.scala:113)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at ammonite.main.Scripts$$anonfun$runScript$2.apply(Scripts.scala:52)
    at ammonite.main.Scripts$$anonfun$runScript$2.apply(Scripts.scala:22)
    at ammonite.util.Res$Success.map(Res.scala:61)
    at ammonite.main.Scripts$.runScript(Scripts.scala:22)
    at ammonite.Main.runScript(Main.scala:82)
    at ammonite.Main$$anonfun$main$1$$anonfun$apply$1.apply(Main.scala:193)
    at ammonite.Main$.ammonite$Main$$ifContinually$1(Main.scala:173)
    at ammonite.Main$$anonfun$main$1.apply(Main.scala:175)
    at ammonite.Main$$anonfun$main$1.apply(Main.scala:175)
    at scala.Option.foreach(Option.scala:257)
    at ammonite.Main$.main(Main.scala:175)
    at ammonite.Main.main(Main.scala)
```

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/lihaoyi/Ammonite/pull/420
