### ISSUE TITLE
update developer/internals docs to mention gotchas

### ISSUE THREAD

**Issue by yakticus** [lihaoyi/Ammonite#449]
e.g., if you import ammonite from `sbt.global` as the user doc mentions, and you try to build Ammonite, then you'll get an error that looks like this:

```
[error] a module is not authorized to depend on itself: com.lihaoyi#ammonite_2.11.8;0.7.4
java.lang.IllegalArgumentException: a module is not authorized to depend on itself: com.lihaoyi#ammonite_2.11.8;0.7.4
    at org.apache.ivy.core.resolve.IvyNodeCallers.addCaller(IvyNodeCallers.java:167)
    at org.apache.ivy.core.resolve.IvyNode.addCaller(IvyNode.java:1076)
<snip>
```

**Comment by lihaoyi** [comment]
This should be fixed now that we're using `version-SNAPSHOT` as the development version and only publishing indexed versions based on tags
