### ISSUE TITLE
crash on updating to 0.7.6

### ISSUE THREAD

**Issue by ckampfe** [lihaoyi/Ammonite#458]
```
clarkkampfe$> brew info ammonite-repl
ammonite-repl: stable 0.7.6
Ammonite is a cleanroom re-implementation of the Scala REPL
https://lihaoyi.github.io/Ammonite/#Ammonite-REPL
/usr/local/Cellar/ammonite-repl/0.7.5 (2 files, 30.7M)
  Built from source on 2016-08-29 at 12:38:30
/usr/local/Cellar/ammonite-repl/0.7.6 (2 files, 30.7M) *
  Built from source on 2016-09-03 at 11:56:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ammonite-repl.rb

clarkkampfe$> amm                                                                                                                                                        [55/1342]
Loading...
Compiling LoadedPredef.sc
:: loading settings :: url = jar:file:/usr/local/Cellar/ammonite-repl/0.7.6/bin/amm!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: com.lihaoyi#ammonite-shell_2.11-caller;working
        confs: [default]
        found com.lihaoyi#ammonite-shell_2.11;0.7.6 in central
        found org.scala-lang#scala-library;2.11.8 in m2
        found com.lihaoyi#ammonite-ops_2.11;0.7.6 in central
        found com.lihaoyi#ammonite_2.11.8;0.7.6 in central
        found com.lihaoyi#ammonite-terminal_2.11;0.7.6 in central
        found com.lihaoyi#sourcecode_2.11;0.1.2 in central
        found com.lihaoyi#fansi_2.11;0.2.0 in central
        found com.lihaoyi#ammonite-util_2.11.8;0.7.6 in central
        found com.lihaoyi#upickle_2.11;0.4.2 in central
        found com.lihaoyi#derive_2.11;0.4.2 in central
        found org.spire-math#jawn-parser_2.11;0.8.3 in central
        found com.lihaoyi#pprint_2.11;0.4.2 in central
        found com.lihaoyi#ammonite-runtime_2.11.8;0.7.6 in central
        found org.apache.ivy#ivy;2.4.0 in central
        found org.scalaj#scalaj-http_2.11;2.3.0 in central
        found com.lihaoyi#ammonite-compiler_2.11.8;0.7.6 in central
        found org.scala-lang#scala-compiler;2.11.8 in chain-resolver
        found org.scala-lang#scala-reflect;2.11.8 in chain-resolver
        [2.11.8] org.scala-lang#scala-reflect;2.11.8
        found org.scala-lang.modules#scala-xml_2.11;1.0.4 in chain-resolver
        found org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4 in chain-resolver
        found com.lihaoyi#scalaparse_2.11;0.3.7 in central
        found com.lihaoyi#fastparse_2.11;0.3.7 in central
        found com.lihaoyi#fastparse-utils_2.11;0.3.7 in central
        found com.lihaoyi#ammonite-repl_2.11.8;0.7.6 in central
        found jline#jline;2.12 in central
        found com.github.scopt#scopt_2.11;3.4.0 in central
        found com.lihaoyi#acyclic_2.11;0.1.4 in m2
Exception in thread "main" java.lang.RuntimeException: Error during Predef:                                                                                              [21/1242]
        at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:138)
        at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:118)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
        at ammonite.runtime.Interpreter.<init>(Interpreter.scala:118)
        at ammonite.repl.Repl.<init>(Repl.scala:43)
        at ammonite.Main.instantiateRepl(Main.scala:61)
        at ammonite.Main.run(Main.scala:107)
        at ammonite.Main$$anonfun$main$1$$anonfun$apply$1.apply(Main.scala:249)
        at ammonite.Main$.ammonite$Main$$ifContinually$1(Main.scala:228)
        at ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
        at ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
        at scala.Option.foreach(Option.scala:257)
        at ammonite.Main$.main(Main.scala:230)
        at ammonite.Main.main(Main.scala)
Caused by: ammonite.runtime.tools.IvyThing$IvyResolutionException: failed to resolve ivy dependencies unresolved dependency: org.scala-lang#scala-library;2.11.8: configuration no
t found in org.scala-lang#scala-library;2.11.8: 'master(compile)'. Missing configuration: 'compile'. It was required from org.scala-lang.modules#scala-parser-combinators_2.11;1.0
.4 compile
        at ammonite.runtime.tools.IvyThing.resolveArtifact(IvyThing.scala:108)
        at ammonite.runtime.Interpreter.loadIvy(Interpreter.scala:592)
        at ammonite.runtime.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:625)
        at ammonite.predef.LoadedPredef$.<init>(LoadedPredef.sc:3)
        at ammonite.predef.LoadedPredef$.<clinit>(LoadedPredef.sc)
        at ammonite.predef.LoadedPredef.$main(LoadedPredef.sc)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ammonite.runtime.Evaluator$$anon$1.evalMain(Evaluator.scala:106)
        at ammonite.runtime.Evaluator$$anon$1$$anonfun$processScriptBlock$1.apply(Evaluator.scala:157)
        at ammonite.runtime.Evaluator$$anon$1$$anonfun$processScriptBlock$1.apply(Evaluator.scala:155)
        at ammonite.util.Catching.map(Res.scala:110)
        at ammonite.runtime.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:155)
        at ammonite.runtime.Interpreter$$anonfun$processScriptBlock$2.apply(Interpreter.scala:311)
        at ammonite.runtime.Interpreter$$anonfun$processScriptBlock$2.apply(Interpreter.scala:303)
        at ammonite.util.Res$Success.flatMap(Res.scala:57)
        at ammonite.runtime.Interpreter.processScriptBlock(Interpreter.scala:303)
        at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29$$anonfun$apply$30.apply(Interpreter.scala:438)
        at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29$$anonfun$apply$30.apply(Interpreter.scala:438)
        at ammonite.runtime.Interpreter.withContextClassloader(Interpreter.scala:248)
        at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29.apply(Interpreter.scala:437)
        at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29.apply(Interpreter.scala:436)
        at ammonite.runtime.Interpreter$$anonfun$27.apply(Interpreter.scala:532)
        at ammonite.runtime.Interpreter$$anonfun$27.apply(Interpreter.scala:521)
        at ammonite.util.Res$Success.flatMap(Res.scala:57)
        at ammonite.runtime.Interpreter.loop$1(Interpreter.scala:521)
        at ammonite.runtime.Interpreter.processCorrectScript(Interpreter.scala:559)
        at ammonite.runtime.Interpreter$$anonfun$processModule0$2.apply(Interpreter.scala:431)
        at ammonite.runtime.Interpreter$$anonfun$processModule0$2.apply(Interpreter.scala:430)
        at ammonite.util.Res$Success.flatMap(Res.scala:57)
        at ammonite.runtime.Interpreter.processModule0(Interpreter.scala:430)
         at ammonite.runtime.Interpreter.processModule(Interpreter.scala:376)
        at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:121)
        ... 15 more
```

**Comment by lihaoyi** [comment]
Ahh that normally means ammonite has messed up your ivy cache. If you `rm -rf ~/.ivy2/cache/org.scala-lang` (and do the same for any others that pop up) that should make things work again.

**Comment by ckampfe** [comment]
you were right! thanks for the tip 👍
