### ISSUE TITLE
Missing configuration: 'compile', with some interp.load.ivy deps in predef.sc on 0.7.6

### ISSUE THREAD

**Issue by emanresusername** [lihaoyi/Ammonite#459]
predef.sc
```scala
interp.load.ivy("com.lihaoyi" %% "ammonite-shell" % ammonite.Constants.version)
interp.load.ivy("net.ruippeixotog" %% "scala-scraper" % "1.0.0")
@
val shellSession = ammonite.shell.ShellSession()
import shellSession._
import ammonite.shell.PPrints._
import ammonite.ops._
import ammonite.shell._
ammonite.shell.Configure(repl, wd)
```
```text
Loading...
Compiling LoadedPredef.sc
:: loading settings :: url = jar:file:/usr/local/Cellar/ammonite-repl/0.7.6/bin/amm!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: net.ruippeixotog#scala-scraper_2.11-caller;working
       	confs: [default]
       	found net.ruippeixotog#scala-scraper_2.11;1.0.0 in chain-resolver
       	found org.scala-lang#scala-compiler;2.11.8 in chain-resolver
       	found org.scala-lang#scala-library;2.11.8 in chain-resolver
       	[2.11.8] org.scala-lang#scala-library;2.11.8
       	found org.scala-lang#scala-reflect;2.11.8 in chain-resolver
       	[2.11.8] org.scala-lang#scala-reflect;2.11.8
       	found org.scala-lang.modules#scala-xml_2.11;1.0.4 in chain-resolver
       	found org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4 in chain-resolver
       	found com.github.nscala-time#nscala-time_2.11;2.12.0 in chain-resolver
       	found joda-time#joda-time;2.9.3 in chain-resolver
       	found org.joda#joda-convert;1.2 in chain-resolver
       	found com.typesafe#config;1.3.0 in chain-resolver
       	found net.sourceforge.htmlunit#htmlunit;2.20 in chain-resolver
       	found xalan#xalan;2.7.2 in chain-resolver
       	found xalan#serializer;2.7.2 in chain-resolver
       	found xml-apis#xml-apis;1.3.04 in chain-resolver
       	found org.apache.commons#commons-lang3;3.4 in chain-resolver
       	found org.apache.httpcomponents#httpclient;4.5.2 in chain-resolver
       	found org.apache.httpcomponents#httpcore;4.4.4 in chain-resolver
       	found commons-logging#commons-logging;1.2 in m2
       	found org.apache.httpcomponents#httpmime;4.5.2 in chain-resolver
       	found commons-codec#commons-codec;1.10 in chain-resolver
       	found net.sourceforge.htmlunit#htmlunit-core-js;2.17 in chain-resolver
       	found xerces#xercesImpl;2.11.0 in chain-resolver
       	found xml-apis#xml-apis;1.4.01 in chain-resolver
       	found net.sourceforge.nekohtml#nekohtml;1.9.22 in chain-resolver
       	found net.sourceforge.cssparser#cssparser;0.9.18 in central
       	found org.w3c.css#sac;1.3 in central
       	found commons-io#commons-io;2.4 in chain-resolver
       	found org.eclipse.jetty.websocket#websocket-client;9.2.15.v20160210 in chain-resolver
       	found org.eclipse.jetty#jetty-util;9.2.15.v20160210 in chain-resolver
       	found org.eclipse.jetty#jetty-io;9.2.15.v20160210 in chain-resolver
       	found org.eclipse.jetty.websocket#websocket-common;9.2.15.v20160210 in chain-resolver
       	found org.eclipse.jetty.websocket#websocket-api;9.2.15.v20160210 in chain-resolver
       	found org.jsoup#jsoup;1.8.3 in chain-resolver
       	found org.scalaz#scalaz-core_2.11;7.2.2 in chain-resolver
       	found org.scoverage#scalac-scoverage-runtime_2.11;1.1.1 in chain-resolver
       	found org.scoverage#scalac-scoverage-plugin_2.11;1.1.1 in chain-resolver
Exception in thread "main" java.lang.RuntimeException: Error during Predef:
       	at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:138)
       	at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:118)
       	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
       	at scala.collection.immutable.List.foreach(List.scala:381)
       	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
       	at ammonite.runtime.Interpreter.<init>(Interpreter.scala:118)
       	at ammonite.repl.Repl.<init>(Repl.scala:43)
       	at ammonite.Main.instantiateRepl(Main.scala:61)
       	at ammonite.Main.run(Main.scala:107)
       	at ammonite.Main$$anonfun$main$1$$anonfun$apply$1.apply(Main.scala:249)
       	at ammonite.Main$.ammonite$Main$$ifContinually$1(Main.scala:228)
       	at ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
       	at ammonite.Main$$anonfun$main$1.apply(Main.scala:230)
       	at scala.Option.foreach(Option.scala:257)
       	at ammonite.Main$.main(Main.scala:230)
       	at ammonite.Main.main(Main.scala)
Caused by: ammonite.runtime.tools.IvyThing$IvyResolutionException: failed to resolve ivy dependencies unresolved dependency: commons-logging#commons-logging;1.2: configuration not found in commons-logging#commons-logging;1.2: 'master(compile)'. Missing configuration: 'compile'. It was required from org.apache.httpcomponents#httpclient;4.5.2 compile
       	at ammonite.runtime.tools.IvyThing.resolveArtifact(IvyThing.scala:108)
       	at ammonite.runtime.Interpreter.loadIvy(Interpreter.scala:592)
       	at ammonite.runtime.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:625)
       	at ammonite.predef.LoadedPredef$.<init>(LoadedPredef.sc:2)
       	at ammonite.predef.LoadedPredef$.<clinit>(LoadedPredef.sc)
       	at ammonite.predef.LoadedPredef.$main(LoadedPredef.sc)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:497)
       	at ammonite.runtime.Evaluator$$anon$1.evalMain(Evaluator.scala:106)
       	at ammonite.runtime.Evaluator$$anon$1$$anonfun$processScriptBlock$1.apply(Evaluator.scala:157)
       	at ammonite.runtime.Evaluator$$anon$1$$anonfun$processScriptBlock$1.apply(Evaluator.scala:155)
       	at ammonite.util.Catching.map(Res.scala:110)
       	at ammonite.runtime.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:155)
       	at ammonite.runtime.Interpreter$$anonfun$processScriptBlock$2.apply(Interpreter.scala:311)
       	at ammonite.runtime.Interpreter$$anonfun$processScriptBlock$2.apply(Interpreter.scala:303)
       	at ammonite.util.Res$Success.flatMap(Res.scala:57)
       	at ammonite.runtime.Interpreter.processScriptBlock(Interpreter.scala:303)
       	at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29$$anonfun$apply$30.apply(Interpreter.scala:438)
       	at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29$$anonfun$apply$30.apply(Interpreter.scala:438)
       	at ammonite.runtime.Interpreter.withContextClassloader(Interpreter.scala:248)
       	at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29.apply(Interpreter.scala:437)
       	at ammonite.runtime.Interpreter$$anonfun$processModule0$2$$anonfun$apply$29.apply(Interpreter.scala:436)
       	at ammonite.runtime.Interpreter$$anonfun$27.apply(Interpreter.scala:532)
       	at ammonite.runtime.Interpreter$$anonfun$27.apply(Interpreter.scala:521)
       	at ammonite.util.Res$Success.flatMap(Res.scala:57)
       	at ammonite.runtime.Interpreter.loop$1(Interpreter.scala:521)
       	at ammonite.runtime.Interpreter.processCorrectScript(Interpreter.scala:559)
       	at ammonite.runtime.Interpreter$$anonfun$processModule0$2.apply(Interpreter.scala:431)
       	at ammonite.runtime.Interpreter$$anonfun$processModule0$2.apply(Interpreter.scala:430)
       	at ammonite.util.Res$Success.flatMap(Res.scala:57)
       	at ammonite.runtime.Interpreter.processModule0(Interpreter.scala:430)
       	at ammonite.runtime.Interpreter.processModule(Interpreter.scala:376)
       	at ammonite.runtime.Interpreter$$anonfun$10.apply(Interpreter.scala:121)
       	... 15 more
```

**Comment by lihaoyi** [comment]
Try to `rm -rf ~/.ivy2/cache/commons-logging`?

**Comment by emanresusername** [comment]
👍

**Comment by timcharper** [comment]
I had a similar error with `commons-lang`.

`rm -rf ~/.ivy2/cache/commons-lang` did not solve it, but `rm -rf ~/.ivy2` did :)
