### ISSUE TITLE
NullPointerException on fansi.Str$.apply

### ISSUE THREAD

**Issue by dportabella** [lihaoyi/Ammonite#463]
Running this code from the Ammonite REPL:

```
import $ivy.`org.apache.spark::spark-core:2.0.0`, org.apache.spark._
import scala.math.random
val conf = new SparkConf().setAppName("SparkAmmonite").setMaster("local[1]")
val sc = new SparkContext(conf)

val slices = 2
val n = math.min(100000L * slices, Int.MaxValue).toInt
val count = sc.parallelize(1 until n, slices).map { i =>
  val x = random * 2 - 1
  val y = random * 2 - 1
  if (x*x + y*y < 1) 1 else 0
}.reduce(_ + _)
println("Pi is roughly " + 4.0 * count / n)
sc.stop()
```

it throws this error, and ammonite REPL stops:

```
Exception in thread "main" java.lang.NullPointerException
    at fansi.Str$.apply(Fansi.scala:301)
    at fansi.Str$.implicitApply(Fansi.scala:268)
    at ammonite.main.Repl$.highlightFrame(Repl.scala:113)
    at ammonite.main.Repl$$anonfun$9$$anonfun$apply$5.apply(Repl.scala:134)
    at ammonite.main.Repl$$anonfun$9$$anonfun$apply$5.apply(Repl.scala:134)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
    at ammonite.main.Repl$$anonfun$9.apply(Repl.scala:134)
    at ammonite.main.Repl$$anonfun$9.apply(Repl.scala:129)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.immutable.List.map(List.scala:285)
    at ammonite.main.Repl$.showException(Repl.scala:129)
    at ammonite.main.Repl.loop$1(Repl.scala:94)
    at ammonite.main.Repl.run(Repl.scala:102)
    at ammonite.Main.run(Main.scala:70)
    at ammonite.Main$$anonfun$main$1$$anonfun$apply$1.apply(Main.scala:191)
    at ammonite.Main$.ammonite$Main$$ifContinually$1(Main.scala:173)
    at ammonite.Main$$anonfun$main$1.apply(Main.scala:175)
    at ammonite.Main$$anonfun$main$1.apply(Main.scala:175)
    at scala.Option.foreach(Option.scala:257)
    at ammonite.Main$.main(Main.scala:175)
    at ammonite.Main.main(Main.scala)
```

Running the same code from a script (`amm myscript.scala`), it throws this other error:

```
Exception in thread "main" java.io.IOException: Class not found
    at org.apache.xbean.asm5.ClassReader.a(Unknown Source)
    at org.apache.xbean.asm5.ClassReader.<init>(Unknown Source)
    at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:42)
    at org.apache.spark.util.ClosureCleaner$.getInnerClosureClasses(ClosureCleaner.scala:83)
    at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:173)
    at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:108)
    at org.apache.spark.SparkContext.clean(SparkContext.scala:2037)
    at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:366)
    at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:365)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
    at org.apache.spark.rdd.RDD.map(RDD.scala:365)
    at $file.a$.<init>(a.sc:8)
    at $file.a$.<clinit>(a.sc)
    at $file.a.$main(a.sc)
```

There is a problem in `myscript.scala` (related to https://github.com/lihaoyi/Ammonite/issues/382) that throws a `java.io.IOException`. **However, it seems at the Ammonite REPL has a bug, when calling Fansi when there is an exception (Fanci is not called without the REPL, and that's why this bug does not show up).**

**Comment by lihaoyi** [comment]
I'm getting Ivy errors trying to repro
```scala
ammonite.runtime.tools.IvyThing$IvyResolutionException: failed to resolve ivy dependencies unresolved dependency: org.scala-lang.modules#scala-xml_2.11;1.0.2: configuration not found in org.scala-lang.modules#scala-xml_2.11;1.0.2: 'master(compile)'. Missing configuration: 'compile'. It was required from org.scalatest#scalatest_2.11;2.2.6 compile
```

**Comment by dportabella** [comment]
I don't know what to say. I tried the example again and I don't have any ivy error. i'll try from another computer.

**Comment by lihaoyi** [comment]
Yeah, we have intermittent ivy problems. It's probably just that, maybe I'll clear my cache and try again when I have time
