### ISSUE TITLE
REPL Installation error: Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 152

### ISSUE THREAD

**Issue by gidsg** [lihaoyi/Ammonite#540]
When I try to install Ammonite REPL I get the following error:

```
$ sudo curl -L -o /usr/local/bin/amm https://git.io/v1rPf && sudo chmod +x /usr/local/bin/amm && amm
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   580    0   580    0     0    639      0 --:--:-- --:--:-- --:--:--     0
100 22.1M  100 22.1M    0     0  1015k      0  0:00:22  0:00:22 --:--:-- 1414k
Loading...
Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 152
Exception Details:
  Location:
    scala/util/matching/Regex.unapplySeq(Ljava/lang/Object;)Lscala/Option; @207: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2bc1 00cc 9900 e92b c000 cc4e 2ab6 0054
    0000010: 2db6 005a 3a04 2a19 04b6 005e 9900 cabb
    0000020: 0060 59b2 0065 b200 6a04 3606 c700 0501
    0000030: bf15 0619 04b6 0070 b600 74b6 0078 1904
    0000040: ba01 0a00 00b2 0093 b600 973a 093a 0859
    0000050: c700 0501 bf3a 0719 09b2 0093 b600 9ba6
    0000060: 0078 1907 b200 a0a6 0009 b200 a0a7 0073
    0000070: bb00 a259 1907 b600 a83a 0e19 0419 0eb8
    0000080: 0108 b200 a0b7 00ac 3a0a 190a 3a0b 1907
    0000090: b600 afc0 00a4 3a0c 190c b200 a0a5 0035
    00000a0: bb00 a259 190c b600 a83a 0e19 0419 0eb8
    00000b0: 0108 b200 a0b7 00ac 3a0d 190b 190d b600
    00000c0: b319 0d3a 0b19 0cb6 00af c000 a43a 0ca7
    00000d0: ffc9 190a a700 0c19 0719 0819 09b8 00b9
    00000e0: b700 bca7 0006 b200 524d a700 212b c100
    00000f0: 2299 0016 2bc0 0022 3a05 2a19 05b6 00ef
    0000100: b601 024d a700 07b2 0052 4d2c b0       
  Stackmap Table:
    full_frame(@49,{Object[#2],Object[#4],Top,Object[#204],Object[#108],Top,Integer},{Uninitialized[#31],Uninitialized[#31],Object[#98]})
    full_frame(@85,{Object[#2],Object[#4],Top,Object[#204],Object[#108],Top,Integer,Top,Object[#206],Object[#208]},{Uninitialized[#31],Uninitialized[#31],Object[#164]})
    full_frame(@112,{Object[#2],Object[#4],Top,Object[#204],Object[#108],Top,Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#31],Uninitialized[#31]})
    full_frame(@152,{Object[#2],Object[#4],Top,Object[#204],Object[#108],Top,Integer,Object[#164],Object[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{Uninitialized[#31],Uninitialized[#31]})
    full_frame(@210,{Object[#2],Object[#4],Top,Object[#204],Object[#108],Top,Integer,Object[#164],Object[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{Uninitialized[#31],Uninitialized[#31]})
    full_frame(@215,{Object[#2],Object[#4],Top,Object[#204],Object[#108],Top,Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#31],Uninitialized[#31]})
    full_frame(@224,{Object[#2],Object[#4],Top,Object[#204],Object[#108],Top,Integer,Object[#164],Object[#206],Object[#208]},{Uninitialized[#31],Uninitialized[#31],Object[#4]})
    full_frame(@230,{Object[#2],Object[#4],Top,Object[#204],Object[#108]},{})
    same_locals_1_stack_item_frame(@233,Object[#210])
    chop_frame(@237,3)
    same_frame(@263)
    append_frame(@267,Object[#210])

	at scala.collection.immutable.StringLike.r(StringLike.scala:287)
	at scala.collection.immutable.StringLike.r$(StringLike.scala:287)
	at scala.collection.immutable.StringOps.r(StringOps.scala:29)
	at scala.collection.immutable.StringLike.r(StringLike.scala:276)
	at scala.collection.immutable.StringLike.r$(StringLike.scala:276)
	at scala.collection.immutable.StringOps.r(StringOps.scala:29)
	at ammonite.runtime.SpecialClassLoader$.<init>(ClassLoaders.scala:37)
	at ammonite.runtime.SpecialClassLoader$.<clinit>(ClassLoaders.scala)
	at ammonite.runtime.Evaluator$$anon$1.initialFrame(Evaluator.scala:80)
	at ammonite.runtime.Evaluator$$anon$1.<init>(Evaluator.scala:89)
	at ammonite.runtime.Evaluator$.apply(Evaluator.scala:59)
	at ammonite.interp.Interpreter.<init>(Interpreter.scala:53)
	at ammonite.repl.Repl.<init>(Repl.scala:41)
	at ammonite.Main.instantiateRepl(Main.scala:68)
	at ammonite.Main.run(Main.scala:108)
	at ammonite.Main$.$anonfun$main$2(Main.scala:250)
	at ammonite.Main$$$Lambda$74/717386707.apply(Unknown Source)
	at ammonite.Main$.ifContinually$1(Main.scala:229)
	at ammonite.Main$.$anonfun$main$1(Main.scala:231)
	at ammonite.Main$$$Lambda$73/1340328248.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.Main$.main(Main.scala:231)
	at ammonite.Main.main(Main.scala)
```
Here is some other environment info:
```
$ java -version
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
```
```
$ scala -version
cat: /release: No such file or directory
Scala code runner version 2.12.1 -- Copyright 2002-2016, LAMP/EPFL and Lightbend, Inc.
```

OSX:
```
$ sw_vers -productVersion 
10.12.2
```

**Comment by gidsg** [comment]
OK I got it to work, I think what fixed it was updating my SBT version.

**Comment by pandemonium** [comment]
I have this very issue right now but upgrading SBT does not seem to help. The one difference (that I know of!) is:

$ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

$ sw_vers -productVersion 
10.12.3

**Comment by DennisVDB** [comment]
It worked for me by updating the JDK.

**Comment by a244591052** [comment]
It worked for me by updating the JDK too.

**Comment by esthom** [comment]
I needed to explicitly remove older JDK versions to proceed.
