### ISSUE TITLE
Exception during macro expansion

### ISSUE THREAD

**Issue by henridwyer** [lihaoyi/Ammonite#575]
Scala 2.12.1
Ammonite 0.8.2

When trying to use google sheets java api to modify google sheets I get the following error:

``` scala
import $ivy.`com.google.apis:google-api-services-sheets:v4-rev462-1.22.0`
import com.google.api.services.sheets.v4.Sheets;
import com.google.api.client.googleapis.javanet.GoogleNetHttpTransport;
import com.google.api.client.json.jackson2.JacksonFactory;

val httpTransport = GoogleNetHttpTransport.newTrustedTransport()
val JSON_FACTORY = JacksonFactory.getDefaultInstance()

val sheets = new Sheets(httpTransport, JSON_FACTORY, null)
sheets.spreadsheets
```

```
cmd7.sc:8: exception during macro expansion:
java.lang.AssertionError: assertion failed: mkAttributedQualifier(com.google.api.services.sheets.v4.Sheets, <none>)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:86)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:62)
	at scala.reflect.internal.TreeGen.mkAttributedRef(TreeGen.scala:146)
	at scala.reflect.internal.Internals$$anon$4.mkAttributedRef(Internals.scala:135)
	at scala.reflect.internal.Internals$$anon$4.mkAttributedRef(Internals.scala:132)
	at derive.Derive.companionTree(Derive.scala:416)
	at derive.Derive.getArgSyms(Derive.scala:387)
	at derive.Derive.onFail$1(Derive.scala:155)
	at derive.Derive.$anonfun$deriveType$5(Derive.scala:212)
	at derive.Derive$$Lambda$1797/1086491405.apply(Unknown Source)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:79)
	at derive.Derive.rec$1(Derive.scala:185)
	at derive.Derive.deriveType(Derive.scala:230)
	at derive.Derive.derive(Derive.scala:60)
	at pprint.Internals$LowerPriPPrint$.liftedTree1$1(PPrint.scala:408)
	at pprint.Internals$LowerPriPPrint$.FinalRepr(PPrint.scala:408)

            .print(res7, res7, "res7", _root_.scala.None)
                  ^
Compilation Failed
```

This might be a duplicate of #455 

Any idea how to work around this?

**Comment by lihaoyi** [comment]
Fixed in https://github.com/lihaoyi/Ammonite/commit/2d78e1fbd4b1adad658d071eb3679f8932bdade8

**Comment by lihaoyi** [comment]
http://www.lihaoyi.com/Ammonite/#0.9.0 is out

**Comment by henridwyer** [comment]
@lihaoyi thanks this works now!
