### ISSUE TITLE
Can't run Repl outside of Scala Repl

### ISSUE THREAD

**Issue by sschaef** [lihaoyi/Ammonite#60]
I defined:
```scala
lazy val a = taskKey[Unit]("Starts Ammonite Repl")
a := {
  ammonite.repl.Repl.main(null)
}
```

but after running it I got:
```
> a
Loading Ammonite Repl...
[trace] Stack trace suppressed: run last *:a for the full output.
[error] (*:a) java.lang.ClassCastException: ammonite.repl.Res$Failure cannot be cast to ammonite.repl.Res$Success
[error] Total time: 0 s, completed Apr 22, 2015 6:34:05 PM
> last *:a
java.lang.ClassCastException: ammonite.repl.Res$Failure cannot be cast to ammonite.repl.Res$Success
	at ammonite.repl.interp.Interpreter.init(Interpreter.scala:128)
	at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:143)
	at ammonite.repl.Repl.<init>(Repl.scala:31)
	at ammonite.repl.Repl$.main(Repl.scala:67)
	at $7f12d7262936b1f262c7$$anonfun$$sbtdef$1.apply$mcV$sp(/home/antoras/.sbt/0.13/global.sbt:16)
	at $7f12d7262936b1f262c7$$anonfun$$sbtdef$1.apply(/home/antoras/.sbt/0.13/global.sbt:15)
	at $7f12d7262936b1f262c7$$anonfun$$sbtdef$1.apply(/home/antoras/.sbt/0.13/global.sbt:15)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:a) java.lang.ClassCastException: ammonite.repl.Res$Failure cannot be cast to ammonite.repl.Res$Success
```

**Comment by lihaoyi** [comment]
my money is on classloader funniness running it in SBT; could you try loading it in a non-SBT Scala program?

**Comment by sschaef** [comment]
Running it outside of sbt works without any problems.

**Comment by sschaef** [comment]
I now run the repl with
```
#!/usr/bin/env scalas

/***
scalaVersion := "2.11.5"
libraryDependencies += "com.lihaoyi" %% "ammonite-repl" % "0.2.7"
*/

ammonite.repl.Repl.main(null)
```
Unfortunately I don't like the default prompt. There is no way right now to set `shellPrompt` through a parameter to `main`?

**Comment by lihaoyi** [comment]
On master, you can pass an argument:

```scala
ammonite.repl.Repl.main("""
shellPrompt = ">>"
""")
```

I haven't published a version yet, but you could publish your own snapshot if you want it nownownow. Otherwise I'll publish 0.3.0 soonish.

Wonder why it doesn't work in SBT though

**Comment by lihaoyi** [comment]
Probably gonna call running inside SBT as "won'tfix" for now

**Comment by sschaef** [comment]
On 04/23/2015 06:53 AM, Li Haoyi wrote:
>
> On master, you can pass an argument:
>
> ammonite.repl.Repl.main("""
> shellPrompt = ">>"
> """)
Thanks, that works. Actually `run` had to be used instead of `main`.
