### ISSUE TITLE
java.lang.IncompatibleClassChangeError when running ammonite

### ISSUE THREAD

**Issue by dispalt** [lihaoyi/Ammonite#603]
I am trying to use the new instructions and have run into a bit of an issue.

I keep getting an `IncompatibleClassChangeError`, so I am guessing something weird is on my classpath.  I have nothing besides the sourceGenerator and the libraryDependency.   
* I got rid of scalatest.
* I checked that all my deps are `2.12` using `dependencyTree`
* I am using jdk8 and scala 2.12.2

I am not totally sure what that means, any ideas?

```scala
Welcome to the Ammonite Repl 0.8.5
(Scala 2.12.2 Java 1.8.0_121)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ val t = "foo"
[error] (run-main-0) java.lang.IncompatibleClassChangeError: Implementing class
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ammonite.repl.Repl.$anonfun$action$2(Repl.scala:89)
	at ammonite.repl.Repl.$anonfun$action$2$adapted(Repl.scala:88)
	at ammonite.repl.AmmoniteFrontEnd.action(AmmoniteFrontEnd.scala:28)
	at ammonite.repl.Repl.action(Repl.scala:88)
	at ammonite.repl.Repl.loop$1(Repl.scala:104)
	at ammonite.repl.Repl.run(Repl.scala:123)
	at ammonite.Main.run(Main.scala:120)
	at amm$.delayedEndpoint$amm$1(amm.scala:1)
	at amm$delayedInit$body.apply(amm.scala:1)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at amm$.main(amm.scala:1)
	at amm.main(amm.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last data/test:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last data/test:run for the full output.
[error] (data/test:run) Nonzero exit code: 1
[error] Total time: 15 s, completed May 18, 2017 9:47:49 PM
```

**Comment by lihaoyi** [comment]
No idea; minimize it?

**Comment by lihaoyi** [comment]
Closing for now; feel free to continue pinging this issue if you have any updates

**Comment by dispalt** [comment]
it seems to work now in `0.9.1`, thanks!
