### ISSUE TITLE
Race condition in code completion

### ISSUE THREAD

**Issue by sschaef** [lihaoyi/Ammonite#61]
Oh my, the poor IDE guys, they are always too blame:

```
Loading Ammonite Repl...
@ ini<tab>
java.lang.AssertionError: assertion failed: Race condition detected: You are running a presentation compiler method outside the PC thread.[phase: <no phase>] Please file a ticket with the current stack trace at https://www.assembla.com/spaces/scala-ide/support/tickets
	at scala.tools.nsc.interactive.Global.assertCorrectThread(Global.scala:459)
	at scala.reflect.internal.Types$UndoLog.undoTo(Types.scala:151)
	at scala.reflect.internal.Types$class.isSameType(Types.scala:5426)
	at scala.reflect.internal.SymbolTable.isSameType(SymbolTable.scala:13)
	at scala.reflect.internal.Types$Type.$eq$colon$eq(Types.scala:923)
	at scala.reflect.internal.Types$class.matchingParams(Types.scala:6387)
	at scala.reflect.internal.Types$class.matchesType(Types.scala:6282)
	at scala.reflect.internal.SymbolTable.matchesType(SymbolTable.scala:13)
	at scala.reflect.internal.Types$Type.matches(Types.scala:943)
	at scala.reflect.internal.Types$Type.findMembers(Types.scala:1118)
	at scala.reflect.internal.Types$Type.membersBasedOnFlags(Types.scala:718)
	at scala.reflect.internal.Types$Type.members(Types.scala:661)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1.ammonite$repl$interp$Pressy$$anon$$anonfun$$rec$1(Pressy.scala:118)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1$$anonfun$6.apply(Pressy.scala:118)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1$$anonfun$6.apply(Pressy.scala:118)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:315)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.reflect.internal.Scopes$Scope.flatMap(Scopes.scala:44)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1.ammonite$repl$interp$Pressy$$anon$$anonfun$$rec$1(Pressy.scala:118)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1$$anonfun$6.apply(Pressy.scala:118)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1$$anonfun$6.apply(Pressy.scala:118)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
	at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:315)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
	at scala.reflect.internal.Scopes$Scope.flatMap(Scopes.scala:44)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1.ammonite$repl$interp$Pressy$$anon$$anonfun$$rec$1(Pressy.scala:118)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1$$anonfun$allDeep$lzycompute$1$1$$anonfun$apply$6.apply(Pressy.scala:127)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1$$anonfun$allDeep$lzycompute$1$1$$anonfun$apply$6.apply(Pressy.scala:126)
	at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:450)
	at scala.collection.immutable.Stream$$anonfun$flatMap$1.apply(Stream.scala:450)
	at scala.collection.immutable.Stream.append(Stream.scala:237)
	at scala.collection.immutable.Stream$$anonfun$append$1.apply(Stream.scala:237)
	at scala.collection.immutable.Stream$$anonfun$append$1.apply(Stream.scala:237)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.scala$collection$immutable$Stream$$loop$4(Stream.scala:849)
	at scala.collection.immutable.Stream$$anonfun$scala$collection$immutable$Stream$$loop$4$1.apply(Stream.scala:850)
	at scala.collection.immutable.Stream$$anonfun$scala$collection$immutable$Stream$$loop$4$1.apply(Stream.scala:850)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
	at scala.collection.immutable.Stream.length(Stream.scala:284)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1.applyOrElse(Pressy.scala:140)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$ammonite$repl$interp$Pressy$$anon$$prefixed$1$1.applyOrElse(Pressy.scala:101)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1505)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1502)
	at scala.reflect.api.Trees$Traverser.traverseStats(Trees.scala:2839)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1134)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1506)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1502)
	at scala.reflect.internal.Trees$$anonfun$itraverse$3.apply$mcV$sp(Trees.scala:1111)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2849)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1110)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1506)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1502)
	at scala.reflect.api.Trees$Traverser.traverseTrees(Trees.scala:2829)
	at scala.reflect.internal.Trees$$anonfun$itraverse$1.apply$mcV$sp(Trees.scala:1103)
	at scala.reflect.api.Trees$Traverser.atOwner(Trees.scala:2849)
	at scala.reflect.internal.Trees$class.itraverse(Trees.scala:1102)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
	at scala.reflect.internal.SymbolTable.itraverse(SymbolTable.scala:13)
	at scala.reflect.api.Trees$Traverser.traverse(Trees.scala:2825)
	at scala.reflect.internal.Trees$CollectTreeTraverser.traverse(Trees.scala:1506)
	at scala.reflect.internal.Trees$TreeContextApiImpl.collect(Trees.scala:92)
	at ammonite.repl.interp.Pressy$$anon$3.ammonite$repl$interp$Pressy$$anon$$prefixed$1(Pressy.scala:101)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$7.apply(Pressy.scala:150)
	at ammonite.repl.interp.Pressy$$anon$3$$anonfun$7.apply(Pressy.scala:150)
	at scala.Option.orElse(Option.scala:257)
	at ammonite.repl.interp.Pressy$$anon$3.complete(Pressy.scala:150)
	at ammonite.repl.Repl$$anonfun$2$$anonfun$apply$2.apply(Repl.scala:27)
	at ammonite.repl.Repl$$anonfun$2$$anonfun$apply$2.apply(Repl.scala:27)
	at ammonite.repl.frontend.JLineFrontend$$anon$1.complete(JLineFrontend.scala:45)
	at jline.console.ConsoleReader.complete(ConsoleReader.java:3261)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2621)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
	at ammonite.repl.frontend.JLineFrontend$$anon$1$$anonfun$action$2.apply(JLineFrontend.scala:71)
	at ammonite.repl.frontend.JLineFrontend$$anon$1$$anonfun$action$2.apply(JLineFrontend.scala:61)
	at ammonite.repl.frontend.Scoped$$anonfun$flatMap$1.apply(Signaller.scala:43)
	at ammonite.repl.frontend.Signaller.apply(Signaller.scala:28)
	at ammonite.repl.frontend.Scoped$class.flatMap(Signaller.scala:43)
	at ammonite.repl.frontend.Signaller.flatMap(Signaller.scala:10)
	at ammonite.repl.frontend.JLineFrontend$$anon$1.action(JLineFrontend.scala:61)
	at ammonite.repl.Repl.action(Repl.scala:42)
	at ammonite.repl.Repl.loop$1(Repl.scala:53)
	at ammonite.repl.Repl.run(Repl.scala:56)
	at ammonite.repl.Repl$.main(Repl.scala:72)
	at .<init>(<console>:9)
	at .<clinit>(<console>)
	at .<init>(<console>:7)
	at .<clinit>(<console>)
	at $print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
	at xsbt.ConsoleInterface$$anon$1.createInterpreter(ConsoleInterface.scala:54)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:839)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
	at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
	at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:904)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lihaoyi** [comment]
This fixed itself in 2.11, and is the reason we haven't been able to run Travis on 2.10.x =/ Thanks for the repro!

**Comment by lihaoyi** [comment]
Do you have reliable instructions for a repro? I've been futzing around with ++2.10.5 and haven't managed to make this happen

**Comment by sschaef** [comment]
I can't reproduce this on the current master. This happened on 0.2.7. But it shouldn't be difficult to fix just by looking on the stack trace. I tried to do it, the only problem is that the line numbers are not correct anymore and I couldn't find any tags for the 0.2.7 release. Do you have a list of the commits that form the releases? Maybe the commit ids are part of the poms?

**Comment by lihaoyi** [comment]
i don't have proper tags, but the commit message says "0.2.7". I'm going to turn on 2.10.x in CI and see if anything blows up
