### ISSUE TITLE
Exception after close repl

### ISSUE THREAD

**Issue by nandotorterolo** [lihaoyi/Ammonite#620]
Welcome to the Ammonite Repl 0.9.6
(Scala 2.12.2 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ Exception in thread "main" java.lang.NullPointerException
	at ammonite.interp.CompilerLifecycleManager.shutdownPressy(CompilerLifecycleManager.scala:131)
	at ammonite.interp.Interpreter.handleOutput(Interpreter.scala:505)
	at ammonite.repl.Repl.loop$1(Repl.scala:97)
	at ammonite.repl.Repl.run(Repl.scala:115)
	at ammonite.Main.run(Main.scala:137)
	at ammonite.Main$.$anonfun$main$1(Main.scala:282)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.Main$.main(Main.scala:260)
	at ammonite.Main.main(Main.scala)
10:46:34 ~$

How to reproduce:
> amm
> CRTL + D

**Comment by lihaoyi** [comment]
Thanks for the report!

**Comment by lihaoyi** [comment]
This should be fixed by https://github.com/lihaoyi/Ammonite/commit/242627f5cdbc7be7a3b9a9fb6082ab9965ff3831; will tag 0.9.7 when CI passes

**Comment by lihaoyi** [comment]
Fixed in 0.9.7
