### ISSUE TITLE
Autocomplete is not working in 0.9.9

### ISSUE THREAD

**Issue by saqibsaleem** [lihaoyi/Ammonite#643]
Overtime I type something and hit tab, I get the following error:

```
@ val n = "aaa"

n: String = "aaa"
@ n.[Current.sc]: exception during background compile: java.lang.AssertionError: assertion failed: (ammonite/predef//~/.ammonite/predef.sc,false,16,16)
java.lang.AssertionError: assertion failed: (ammonite/predef//~/.ammonite/predef.sc,false,16,16)
@ n.      at scala.reflect.io.AbstractFile.lookupPathUnchecked(AbstractFile.scala:225)
	at scala.tools.nsc.settings.MutableSettings$OutputDirs.srcFilesFor(MutableSettings.scala:349)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:881)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$17(ClassfileParser.scala:1048)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:1048)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:489)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:156)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:127)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:316)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:218)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.load(SymbolLoaders.scala:234)
	at scala.tools.nsc.typechecker.Typers$Typer.isStale(Typers.scala:515)
	at scala.tools.nsc.typechecker.Typers$Typer.reallyExists(Typers.scala:506)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectInternal$1(Typers.scala:4892)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:4856)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:4983)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5511)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5527)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5644)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5652)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$importSig(Namers.scala:1687)
	at scala.tools.nsc.typechecker.Namers$Namer$ImportTypeCompleter.completeImpl(Namers.scala:873)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1946)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1944)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1939)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1521)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1669)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3063)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$9(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5176)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5479)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5620)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:423)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:416)
	at scala.tools.nsc.interactive.Global$TyperRun.$anonfun$applyPhase$1(Global.scala:1326)
	at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1326)
	at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1319)
	at scala.tools.nsc.interactive.Global.typeCheck(Global.scala:657)
	at scala.tools.nsc.interactive.Global.$anonfun$backgroundCompile$7(Global.scala:572)
	at scala.tools.nsc.interactive.Global.$anonfun$backgroundCompile$6(Global.scala:568)
	at scala.tools.nsc.interactive.Global.$anonfun$backgroundCompile$6$adapted(Global.scala:568)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:568)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25)
[Current.sc] marking unit as crashed (crashedFiles: Set(Current.sc))
```

Note: I have removed any path information from the error pasted above.

**Comment by lihaoyi** [comment]
Let's keep all autocomplete problems under https://github.com/lihaoyi/Ammonite/issues/275
