### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by scalway** [lihaoyi/Ammonite#669]
```
java.nio.file.FileSystemException: 
/home/slovic/.ammonite/cache/1.0.0/compile/ammonite/$file/Projekty/scalway/sth123123$u002Epl/code/app$minusserver/app$minusserver/app/_experiments/lectionary2/43f2b40cd0b84249631fe3c04939c311/6b07e0957d4674ca6be78a38f8e6e714/ammonite.$file.Projekty.scalway.sth123123$u002Epl.code.app$minusserver.app$minusserver.app._experiments.lectionary2$Parse$$anonfun$ammonite$$file$Projekty$scalway$sth123123$u002Epl$code$app$minusserver$app$minusserver$app$_experiments$lectionary2$Parse$$applyToLiturgy$1$8.class: Filename too long.
```

it seems that generated file has a really long name :(

**Comment by lihaoyi** [comment]
Yeah it does. We could definitely make it more compact. 

One problem is that we make use of the Scala compiler special-operator-encoding to convert our Scala-names into filesystem-safe-paths.:

- https://github.com/lihaoyi/Ammonite/blob/2fef3897f85c91bbec90372d4cdf06c94fc88e81/amm/util/src/main/scala/ammonite/util/Util.scala#L104

This escapes a lot more characters than is strictly necessary for the filesystem, and ends up expanding the file path more than necessary. Specifically, all the `$minus`s don't need to be expanded, nor does the `$u002E` (which is just a `.`)

The other problem is that it seems we duplicate the package path in both the folder-path as well as the name of the classfile. This is wasteful and unnecessary, and doubles the length of the overall filepath. The place to look is probably somewhere around here:

- https://github.com/lihaoyi/Ammonite/blob/a42e78b1ad908e8d63acb09a311601ab35bfc7f5/amm/runtime/src/main/scala/ammonite/runtime/Storage.scala#L191-L215

Both these issues should be relatively easy to fix, so feel free to take a crack at fixing them!

**Comment by piotrkwiecinski** [comment]
@lihaoyi I can give it a try if @scalway doesn't have time.

**Comment by lihaoyi** [comment]
@piotrkwiecinski go for it, no need to wait for people. The more people who are familiarized with the Ammonite codebase the better

**Comment by scalway** [comment]
I've jump this problem by running `amm` with symlink but even with that problem appears  e.g. with upickle:

```
java.nio.file.FileSystemException: /home/slovic/.ammonite/cache/1.0.0/compile/ammonite/$file/lectionary2/84f19e33d4b4a2c7bf7cc3f7a602c40b/eeb420af69d91a5c0b04e75a2104fbc4/ammonite.$file.lectionary2$$anonfun$45$$anon$1$$anonfun$derive$macro$1$1$$anonfun$apply$61$$anon$9$$anonfun$derive$macro$101$1$$anonfun$apply$67$$anon$13$$anonfun$derive$macro$154$1$$anonfun$apply$71$$anon$15$$anonfun$derive$macro$181$1$$anonfun$apply$72.

**Comment by piotrkwiecinski** [comment]
@scalway are you able to provide small reproducer? As regular files look ok. In theory we could drop duplicated $file / directory. It would be easier for me to debug.

**Comment by scalway** [comment]
this is a simple code that fails, mostly because of macros in upickle. 
```scala
import $ivy.`com.lihaoyi::upickle:0.4.4`

object model {
  case class A()
  case class B(a:List[A] = Nil)
  case class C(b:List[B] = Nil)
  case class D(c:List[C] = Nil)
  val EmptyDay = B()
}

import model._

@main def try2Read() = {
  import upickle.default._
  read[D]("{}")
}
```

```java.nio.file.FileSystemException: /home/slovic/.ammonite/cache/1.0.0/compile/ammonite/$file/example/fc3e4442fe34874f08329c7db4051ca8/5445f66659f65b7edb2583ccddf49451/ammonite.$file.example$$anonfun$try2Read$1$$anon$1$$anonfun$derive$macro$1$1$$anonfun$apply$14$$anon$9$$anonfun$derive$macro$49$1$$anonfun$apply$20$$anon$13$$anonfun$derive$macro$73$1$$anonfun$apply$23$$anon$15$$anonfun$derive$macro$85$1$$anonfun$apply$24.class: Filename too long
```

tomorrow I'll try to create a minimal example that doesn't use upickle.

**Comment by lihaoyi** [comment]
The unnecessary escaping should be pretty easy to reproduce it by creating a file with lots of escaped characters, e.g. `.`s. Here is a repro on my mac:

```scala
lihaoyi ~$ echo "println(1337)" > "...........................................................scala"
lihaoyi ~$ amm "...........................................................scala"
Compiling /Users/lihaoyi/...........................................................scala
1337
java.nio.file.FileSystemException: /Users/lihaoyi/.ammonite/cache/1.0.1/compile/ammonite/$file/$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E/c010dd73b31f8736a163869c0f0b1db8/093531daedeab243463d6fadde888866/metadata.json: File name too long
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at ammonite.ops.write$.write(FileOps.scala:278)
	at ammonite.ops.write$over$.apply(FileOps.scala:316)
	at ammonite.runtime.Storage$Folder.compileCacheSave(Storage.scala:197)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$5(Interpreter.scala:288)
	at ammonite.util.Res$Success.map(Res.scala:61)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$4(Interpreter.scala:280)
	at ammonite.util.Res$Success.flatMap(Res.scala:56)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$3(Interpreter.scala:278)
	at ammonite.util.Res$Success.flatMap(Res.scala:56)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$1(Interpreter.scala:275)
	at ammonite.util.Catching.flatMap(Res.scala:109)
	at ammonite.interp.Interpreter.processSingleBlock(Interpreter.scala:274)
	at ammonite.interp.Interpreter.$anonfun$processModule$8(Interpreter.scala:343)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$3(Interpreter.scala:469)
	at ammonite.util.Res$Success.flatMap(Res.scala:56)
	at ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:457)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:513)
	at ammonite.util.Res$Success.flatMap(Res.scala:56)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:512)
	at ammonite.util.Res$Success.flatMap(Res.scala:56)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:509)
	at scala.Option.getOrElse(Option.scala:121)
	at ammonite.interp.Interpreter.loop$1(Interpreter.scala:509)
	at ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:545)
	at ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:345)
	at ammonite.util.Catching.flatMap(Res.scala:109)
	at ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:336)
	at ammonite.util.Res$Success.flatMap(Res.scala:56)
	at ammonite.interp.Interpreter.processModule(Interpreter.scala:328)
	at ammonite.main.Scripts$.$anonfun$runScript$1(Scripts.scala:62)
	at ammonite.util.Res$Success.flatMap(Res.scala:56)
	at ammonite.main.Scripts$.runScript(Scripts.scala:42)
	at ammonite.Main.runScript(Main.scala:210)
	at ammonite.MainRunner.$anonfun$runScript$1(Main.scala:350)
	at ammonite.MainRunner.watchLoop(Main.scala:336)
	at ammonite.MainRunner.runScript(Main.scala:350)
	at ammonite.Main$.main0(Main.scala:290)
	at ammonite.Main$.main(Main.scala:241)
	at ammonite.Main.main(Main.scala)
java.nio.file.FileSystemException: /Users/lihaoyi/.ammonite/cache/1.0.1/compile/ammonite/$file/$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E$u002E/c010dd73b31f8736a163869c0f0b1db8/093531daedeab243463d6fadde888866/metadata.json: File name too long
  sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
  java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
  java.nio.file.Files.newOutputStream(Files.java:216)
  ammonite.ops.write$.write(FileOps.scala:278)
  ammonite.ops.write$over$.apply(FileOps.scala:316)
  ammonite.runtime.Storage$Folder.compileCacheSave(Storage.scala:197)
  ammonite.interp.Interpreter.$anonfun$processSingleBlock$5(Interpreter.scala:288)
  ammonite.util.Res$Success.map(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processSingleBlock$4(Interpreter.scala:280)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processSingleBlock$3(Interpreter.scala:278)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processSingleBlock$1(Interpreter.scala:275)
  ammonite.util.Catching.flatMap(Res.scala:109)
  ammonite.interp.Interpreter.processSingleBlock(Interpreter.scala:274)
  ammonite.interp.Interpreter.$anonfun$processModule$8(Interpreter.scala:343)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$3(Interpreter.scala:469)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:457)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:513)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:512)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:509)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:509)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:545)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:345)
  ammonite.util.Catching.flatMap(Res.scala:109)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:336)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:328)
  ammonite.main.Scripts$.$anonfun$runScript$1(Scripts.scala:62)
  ammonite.util.Res$Success.flatMap(Res.scala:56)
  ammonite.main.Scripts$.runScript(Scripts.scala:42)
  ammonite.Main.runScript(Main.scala:210)
  ammonite.MainRunner.$anonfun$runScript$1(Main.scala:350)
  ammonite.MainRunner.watchLoop(Main.scala:336)
  ammonite.MainRunner.runScript(Main.scala:350)
  ammonite.Main$.main0(Main.scala:290)
  ammonite.Main$.main(Main.scala:241)
  ammonite.Main.main(Main.scala)
```

Now, some characters *have* to be escaped on various operating systems (https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words) but we can probably get away with escaping fewer than we currently do. That won't *solve* the problem, but it would mitigate it. e.g. This won't solve the case where the file name is `<<<<<.scala`, because `<` is reserved on windows so we have to escape it regardless. It won't help @scalway's case because his filename is long due to macro-generated code, not escape characters.

As mentioned above, we currently duplicate the package name in the classfile name for some reason, which we probably can get away with not doing since the package names are already used for the folder the file is in. This will slightly mitigate @scalway's repro, but not by much. A few more degrees of nesting and it'll overshoot 255 characters again.

There are other creative solutions we could try, e.g. if a filename overshoots 255 characters, truncate it to 200 characters + the 40-char SHA of the filename. SHAs are unique enough that they probably won't collide in the lifetime of the universe, and will ensure filenames don't overshoot 240 characters. That would be enough for OS-X, though you should research other OSs like Linux/Windows to see what the restrictions are there.

Lastly, we could store classfiles in a database of some sort. I'd like to avoid that, because it makes the storage much more opaque than flat files, but worst come to worst we can do that.

**Comment by scalway** [comment]
most of the filesystems popular in Linux is limited to 255 bytes. NTFS also look similar, but FAT32 cannot handle such files.

https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

> There are other creative solutions we could try, e.g. if a filename overshoots 255 characters, truncate it to 200 characters + the 40-char SHA of the filename. SHAs are unique enough that they probably won't collide in the lifetime of the universe, and will ensure filenames don't overshoot 240 characters. That would be enough for OS-X, though you should research other OSs like Linux/Windows to see what the restrictions are there.

I like this idea. This could fix all such problems, even this with macro expansion.

**Comment by emanresusername** [comment]
[related?](https://issues.scala-lang.org/browse/SI-3623?focusedCommentId=76104&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-76104)

**Comment by emanresusername** [comment]
[or this](https://stackoverflow.com/a/32862972)?
