### ISSUE TITLE
ls.rec fails if a single file is inaccesible

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#679]
When doing `ls.rec` over `/home/david`, I get this exception:

```
java.nio.file.AccessDeniedException: /home/david/.cache/dconf
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
        at java.nio.file.Files.newDirectoryStream(Files.java:457)
        at ammonite.ops.ls$iter$.$anonfun$apply$6(FileOps.scala:210)
        at geny.Generator$SelfClosing.generate(Generator.scala:219)
        at geny.Generator$Filtered.generate(Generator.scala:269)
        at geny.Generator$FlatMapped.generate(Generator.scala:284)
        at geny.Generator$Concat.generate(Generator.scala:236)
        at geny.Generator$Mapped.generate(Generator.scala:276)
        at geny.Generator$FlatMapped.$anonfun$generate$5(Generator.scala:285)
        at geny.Generator$Filtered.$anonfun$generate$3(Generator.scala:269)
        at geny.Generator$SelfClosing.generate(Generator.scala:222)
        at geny.Generator$Filtered.generate(Generator.scala:269)
        at geny.Generator$FlatMapped.generate(Generator.scala:284)
        at geny.Generator$Concat.generate(Generator.scala:236)
        at geny.Generator$Mapped.generate(Generator.scala:276)
        at geny.Generator$FlatMapped.$anonfun$generate$5(Generator.scala:285)
        at geny.Generator$Filtered.$anonfun$generate$3(Generator.scala:269)
        at geny.Generator$SelfClosing.generate(Generator.scala:222)
        at geny.Generator$Filtered.generate(Generator.scala:269)
        at geny.Generator$FlatMapped.generate(Generator.scala:284)
        at geny.Generator$Mapped.generate(Generator.scala:276)
        at geny.Generator.foreach(Generator.scala:48)
        at geny.Generator.foreach$(Generator.scala:48)
        at geny.Generator$Mapped.foreach(Generator.scala:274)
        at geny.Generator.toBuffer(Generator.scala:120)
        at geny.Generator.toBuffer$(Generator.scala:118)
        at geny.Generator$Mapped.toBuffer(Generator.scala:274)
        at geny.Generator.toVector(Generator.scala:128)
        at geny.Generator.toVector$(Generator.scala:128)
        at geny.Generator$Mapped.toVector(Generator.scala:274)
        at ammonite.ops.ls$.materialize(FileOps.scala:205)
        at ammonite.ops.ls$Walker.materialize(FileOps.scala:237)
        at ammonite.ops.ls$Walker.materialize(FileOps.scala:233)
        at ammonite.ops.StreamableOp1.apply(FileOps.scala:68)
        at ammonite.ops.StreamableOp1.apply$(FileOps.scala:68)
        at ammonite.ops.ls$Walker.apply(FileOps.scala:233)
        at ammonite.ops.ls$Walker.apply(FileOps.scala:233)
        at ammonite.ops.ImplicitOp.$bang(FileOps.scala:194)
        at ammonite.ops.ImplicitOp.$bang$(FileOps.scala:194)
        at ammonite.ops.ls$Walker.$bang(FileOps.scala:233)
```

I expect to obtain a list of accessible files, or, at least an easy way of doing so.

**Comment by piotrkwiecinski** [comment]
@DavidPerezIngeniero I have more or less working solution for it. It's kinda ugly for. I'll try to make it cleaner and will try to add tests and make PR after.

**Comment by DavidPerezIngeniero** [comment]
Thanks piotrkwiecinski!
