### ISSUE TITLE
Using a Scala testing framework in ammonite scripts

### ISSUE THREAD

**Issue by abhi18av** [lihaoyi/Ammonite#701]
Hi @lihaoyi 

I have been trying to use `ammonite` with `scalatest` and `utest` in the context of testing a selenium driver script. 

With this example  [on scalatest](http://www.scalatest.org/user_guide/writing_your_first_test)  I keep running into this error 
```sh

(new StackSpec).execute()
java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
  org.scalactic.Requirements$RequirementsHelper.macroRequireNonNull(Requirements.scala:184)
  org.scalatest.SuperEngine.checkRegisterTestParamsForNull(Engine.scala:725)
  org.scalatest.SuperEngine.registerTest(Engine.scala:644)
  org.scalatest.FlatSpecLike$class.org$scalatest$FlatSpecLike$$registerTestToRun(FlatSpecLike.scala:143)
  org.scalatest.FlatSpecLike$InAndIgnoreMethods.in(FlatSpecLike.scala:1398)
  ammonite.$sess.cmd3$StackSpec.<init>(cmd3.sc:3)
  ammonite.$sess.cmd4$.<init>(cmd4.sc:1)
  ammonite.$sess.cmd4$.<clinit>(cmd4.sc)


```

With [standalone-example test](https://github.com/lihaoyi/utest#running-utest-standalone) case in the `utest`  readme , a `macro` related error is thrown

```sh
Compiling /Users/eklavya/Projects/ProjectEklavya/BlueCollar/devnagri-ui-test-clj/_resources/ammonite-utest.scala
ammonite-utest.scala:9: exception during macro expansion:
java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.tl$1()Lscala/collection/immutable/List;
	at utest.Tests$Builder$$anonfun$utest$Tests$Builder$$matcher$1$1$$anon$13.unapply(Tests.scala:51)
	at utest.Tests$Builder$$anonfun$utest$Tests$Builder$$matcher$1$1.isDefinedAt(Tests.scala:51)
	at utest.Tests$Builder$$anonfun$utest$Tests$Builder$$matcher$1$1.isDefinedAt(Tests.scala:47)
	at utest.Tests$Builder$$anonfun$1.apply(Tests.scala:61)
	at utest.Tests$Builder$$anonfun$1.apply(Tests.scala:61)
	at scala.collection.TraversableLike.$anonfun$partition$1(TraversableLike.scala:314)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.partition(TraversableLike.scala:314)
	at scala.collection.TraversableLike.partition$(TraversableLike.scala:312)
	at scala.collection.AbstractTraversable.partition(Traversable.scala:104)
	at utest.Tests$Builder$.utest$Tests$Builder$$recurse$1(Tests.scala:61)
	at utest.Tests$Builder$.applyImpl(Tests.scala:124)

val tests = Tests{
                 ^
Compilation Failed


```

**Comment by abhi18av** [comment]
The ammonite system information in my case is 
 ```sh
Welcome to the Ammonite Repl 1.0.2
(Scala 2.12.3 Java 1.8.0_131)
```

**Comment by piotrkwiecinski** [comment]
@abhi18av I've tested scalatest for now. 

```bash
Welcome to the Ammonite Repl 1.0.2
(Scala 2.12.3 Java 1.8.0_144)

@ import $ivy.`org.scalatest::scalatest:3.0.1` 
import $ivy.$                               
@ import org.scalatest.FunSuite 
import org.scalatest.FunSuite 
@ class SetSuite extends FunSuite {
             
               test("An empty Set should have size 0") {
                 assert(Set.empty.size == 0)
               }
             
               test("Invoking head on an empty Set should produce NoSuchElementException") {
                 assertThrows[NoSuchElementException] {
                   Set.empty.head
                 }
               }
             } 
defined class SetSuite
@ (new SetSuite).execute() 
cmd2$SetSuite:
- An empty Set should have size 0
- Invoking head on an empty Set should produce NoSuchElementException
@ import org.scalatest.FlatSpec 
import org.scalatest.FlatSpec
@ import collection.mutable.Stack 
import collection.mutable.Stack
@ import org.scalatest._ 
import org.scalatest._
@ class StackSpec extends FlatSpec {
             
               "A Stack" should "pop values in last-in-first-out order" in {
                 val stack = new Stack[Int]
                 stack.push(1)
                 stack.push(2)
                 assert(stack.pop() === 2)
                 assert(stack.pop() === 1)
               }
             
               it should "throw NoSuchElementException if an empty stack is popped" in {
                 val emptyStack = new Stack[String]
                 assertThrows[NoSuchElementException] {
                   emptyStack.pop()
                 }
               }
             } 
defined class StackSpec
@ (new StackSpec).execute() 
cmd7$StackSpec:
A Stack
- should pop values in last-in-first-out order
- should throw NoSuchElementException if an empty stack is popped
```

**Comment by lihaoyi** [comment]
The standalone uTest cases you link work perfectly fine in my version of Ammonite

```scala
lihaoyi utest$ amm
Loading...
Welcome to the Ammonite Repl 1.0.2
(Scala 2.12.3 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ interp.load.ivy( "com.lihaoyi" %% "utest" % "0.5.3")


@ import utest._
import utest._

@ val tests = Tests{
    'test1 - {
      // throw new Exception("test1")
    }
    'test2 - {
      'inner - {
        1
      }
    }
    'test3 - {
      val a = List[Byte](1, 2)
      // a(10)
    }
  }

tests: Tests = Tests(
  Tree(
    "",
    WrappedArray(
      Tree("test1", WrappedArray()),
      Tree("test2", WrappedArray(Tree("inner", WrappedArray()))),
      Tree("test3", WrappedArray())
    )
  ),
  utest.framework.TestCallTree@3611153f
)

@

@ // Run and return results

@ val results1 = TestRunner.run(tests)
results1: framework.HTree[String, framework.Result] = Node(
  "",
  ArrayBuffer(
    Leaf(Result("test1", Success(()), 5L)),
    Node("test2", ArrayBuffer(Leaf(Result("inner", Success(1), 0L)))),
    Leaf(Result("test3", Success(()), 0L))
  )
)

@ val results1 = TestRunner.runAndPrint(tests)
cmd4.sc:1: not enough arguments for method runAndPrint: (tests: utest.Tests, label: String, query: Seq[utest.framework.Tree[String]], printStream: java.io.PrintStream, executor: utest.framework.Executor, formatter: utest.framework.Formatter, ec: scala.concurrent.ExecutionContext)utest.framework.HTree[String,utest.framework.Result].
Unspecified value parameter label.
val results1 = TestRunner.runAndPrint(tests)
                                     ^
Compilation Failed

@ val results1 = TestRunner.runAndPrint(tests, "MySuite")
+ MySuite.test1 0ms
+ MySuite.test2.inner 0ms  1
+ MySuite.test3 0ms
results1: framework.HTree[String, framework.Result] = Node(
  "",
  ArrayBuffer(Leaf(Result("test1", Success(()), 0L)), Node("test2", ArrayBuffer(Leaf(Result("inner", Success(1), 0L)))), Leaf(Result("test3", Success(()), 0L)))
)
```

**Comment by abhi18av** [comment]
Hmm @piotrkwiecinski  and @lihaoyi  both these examples work fine on my machine too.

But the error that I had was to introduce a scala/ java library into a session and then load it. 

For example, **Li Haoyi**  used `interp.load.ivy( "com.lihaoyi" %% "utest" % "0.5.3")` for this purpose but 
**Piotr** used `import $ivy.`org.scalatest::scalatest:3.0.1`` for the same

What I was doing is `import $ivy.`org.scalatest::scalatest:3.0.1`` in the session and then import it and try to use it, in which case it throws the error. Have I missed something in the docs?

The issue is closed now, but I'd appreciate learning more about `ammonite`.

**Comment by lihaoyi** [comment]
Seems to work fine using `import $ivy` and `utest` too
```scala
lihaoyi ~$ amm
Loading...
Welcome to the Ammonite Repl 1.0.2
(Scala 2.12.3 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`com.lihaoyi::utest:0.5.3`
import $ivy.$

@ import utest._
import utest._

@ val tests = Tests{
      'test1 - {
        // throw new Exception("test1")
      }
      'test2 - {
        'inner - {
          1
        }
      }
      'test3 - {
        val a = List[Byte](1, 2)
        // a(10)
      }
    }
tests: Tests = Tests(
  Tree(
    "",
    WrappedArray(
      Tree("test1", WrappedArray()),
      Tree("test2", WrappedArray(Tree("inner", WrappedArray()))),
      Tree("test3", WrappedArray())
    )
  ),
  utest.framework.TestCallTree@75d7297d
)

@ val results1 = TestRunner.runAndPrint(tests, "MySuite")
+ MySuite.test1 5ms
+ MySuite.test2.inner 0ms  1
+ MySuite.test3 0ms
results1: framework.HTree[String, framework.Result] = Node(
  "",
  ArrayBuffer(
    Leaf(Result("test1", Success(()), 5L)),
    Node("test2", ArrayBuffer(Leaf(Result("inner", Success(1), 0L)))),
    Leaf(Result("test3", Success(()), 0L))
  )
)

@
```

**Comment by abhi18av** [comment]
Hmm, it seems I was making some silly mistake of just neglected to read the docs.

In any case I appreciate your time and patience @piotrkwiecinski  and @lihaoyi 👍
