### ISSUE TITLE
Unable to start Ammonite with custom JAVA. JAVA_HOME env var not working.

### ISSUE THREAD

**Issue by tarlov** [lihaoyi/Ammonite#742]
I`m trying to start amm on old server where java has been install from tarball. Even I set java home to 
following 
env | grep JAVA
JAVA_HOME=/opt/java/jdk1.8.0_161/
I receive:
Exception in thread "main" java.lang.UnsupportedClassVersionError: ammonite/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by sake92** [comment]
The `PATH` environment variable decides the search for executables.  
Setting `JAVA_HOME` doesn't necessarily mean it is included in `PATH`...  
Can you try `which java` in terminal and see where it points to?

**Comment by lihaoyi** [comment]
closing due to inactivity
