### ISSUE TITLE
Installation instructions point at stale (0.8.1) version

### ISSUE THREAD

**Issue by gkossakowski** [lihaoyi/Ammonite#753]
Following http://ammonite.io/#ScalaScripts
and running
```
$ sudo curl -L -o /usr/local/bin/amm https://git.io/vdNv2 && sudo chmod +x /usr/local/bin/amm && amm
```

I get

```
Compiling LoadedPredef.sc
:: loading settings :: url = jar:file:/Users/gkk/bin/amm!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: com.lihaoyi#ammonite-shell_2.12.1-caller;working
	confs: [default]

:: problems summary ::
:::: WARNINGS
		module not found: com.lihaoyi#ammonite-shell_2.12.1;0.8.1

	==== local: tried

	  /Users/gkk/.ivy2/local/com.lihaoyi/ammonite-shell_2.12.1/0.8.1/ivys/ivy.xml

	  -- artifact com.lihaoyi#ammonite-shell_2.12.1;0.8.1!ammonite-shell_2.12.1.jar:

	  /Users/gkk/.ivy2/local/com.lihaoyi/ammonite-shell_2.12.1/0.8.1/jars/ammonite-shell_2.12.1.jar

	==== m2: tried

	  /Users/gkk/.m2/repository/com/lihaoyi/ammonite-shell_2.12.1/0.8.1/ivy-0.8.1.xml

	  -- artifact com.lihaoyi#ammonite-shell_2.12.1;0.8.1!ammonite-shell_2.12.1.jar:

	  /Users/gkk/.m2/repository/com/lihaoyi/ammonite-shell_2.12.1/0.8.1/ammonite-shell_2.12.1-0.8.1.jar

	==== central: tried

	  http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.12.1/0.8.1/ammonite-shell_2.12.1-0.8.1.pom

	  -- artifact com.lihaoyi#ammonite-shell_2.12.1;0.8.1!ammonite-shell_2.12.1.jar:

	  http://repo1.maven.org/maven2/com/lihaoyi/ammonite-shell_2.12.1/0.8.1/ammonite-shell_2.12.1-0.8.1.jar


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: Error during Predef:
	at ammonite.interp.Interpreter.$anonfun$new$4(Interpreter.scala:140)
	at ammonite.interp.Interpreter.$anonfun$new$4$adapted(Interpreter.scala:120)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at ammonite.interp.Interpreter.<init>(Interpreter.scala:120)
	at ammonite.repl.Repl.<init>(Repl.scala:41)
	at ammonite.Main.instantiateRepl(Main.scala:68)
	at ammonite.Main.run(Main.scala:108)
	at ammonite.Main$.$anonfun$main$2(Main.scala:250)
	at ammonite.Main$.ifContinually$1(Main.scala:229)
	at ammonite.Main$.$anonfun$main$1(Main.scala:231)
	at scala.Option.foreach(Option.scala:257)
	at ammonite.Main$.main(Main.scala:231)
	at ammonite.Main.main(Main.scala)
Caused by: ammonite.runtime.tools.IvyThing$IvyResolutionException: failed to resolve ivy dependencies unresolved dependency: com.lihaoyi#ammonite-shell_2.12.1;0.8.1: not found
	at ammonite.runtime.tools.IvyThing.resolveArtifact(IvyThing.scala:108)
	at ammonite.interp.Interpreter.loadIvy(Interpreter.scala:603)
	at ammonite.interp.Interpreter$DefaultLoadJar.ivy(Interpreter.scala:632)
	at ammonite.predef.LoadedPredef$.<init>(/Users/gkk/stripe/bazel-chaos-monkey/LoadedPredef.sc:1)
	at ammonite.predef.LoadedPredef$.<clinit>(/Users/gkk/stripe/bazel-chaos-monkey/LoadedPredef.sc)
	at ammonite.predef.LoadedPredef.$main(/Users/gkk/stripe/bazel-chaos-monkey/LoadedPredef.sc)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at ammonite.runtime.Evaluator$$anon$1.evalMain(Evaluator.scala:106)
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processScriptBlock$1(Evaluator.scala:157)
	at ammonite.util.Catching.map(Res.scala:111)
	at ammonite.runtime.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:155)
	at ammonite.interp.Interpreter.$anonfun$processScriptBlock$2(Interpreter.scala:313)
	at ammonite.util.Res$Success.flatMap(Res.scala:58)
	at ammonite.interp.Interpreter.processScriptBlock(Interpreter.scala:305)
	at ammonite.interp.Interpreter.$anonfun$processModule0$4(Interpreter.scala:448)
	at ammonite.interp.Interpreter.withContextClassloader(Interpreter.scala:250)
	at ammonite.interp.Interpreter.$anonfun$processModule0$3(Interpreter.scala:441)
	at ammonite.interp.Interpreter.$anonfun$processModule0$3$adapted(Interpreter.scala:439)
	at ammonite.interp.Interpreter.$anonfun$processCorrectScript$5(Interpreter.scala:539)
	at ammonite.util.Res$Success.flatMap(Res.scala:58)
	at ammonite.interp.Interpreter.loop$1(Interpreter.scala:528)
	at ammonite.interp.Interpreter.processCorrectScript(Interpreter.scala:566)
	at ammonite.interp.Interpreter.$anonfun$processModule0$2(Interpreter.scala:452)
	at ammonite.util.Res$Success.flatMap(Res.scala:58)
	at ammonite.interp.Interpreter.processModule0(Interpreter.scala:433)
	at ammonite.interp.Interpreter.processModule(Interpreter.scala:380)
	at ammonite.interp.Interpreter.$anonfun$new$4(Interpreter.scala:129)
	... 14 more
```

**Comment by gkossakowski** [comment]
nvm, I think I had an old installation of ammonite at `~/bin/amm`. once that is deleted, the instructions work fine
