### ISSUE TITLE
sshd repl on kubernetes "connection to localhost closed"

### ISSUE THREAD

**Issue by AndyMoreland** [lihaoyi/Ammonite#760]
Hi,

I tried to add the sshd repl to a lagom application being deployed in docker on kubernetes on google kubernetes engine.

We're using:

```
"com.lihaoyi" % "ammonite" % "1.0.5" 
"com.lihaoyi" % "ammonite-sshd" % "1.0.5"
```

I'm booting it with:

```
  private lazy val replServer = new SshdRepl(
    sshConfig = SshServerConfig(
      address = "localhost",
      port = 12345,
      passwordAuthenticator = Some(AcceptAllPasswordAuthenticator.INSTANCE),
      publicKeyAuthenticator = None,
      hostKeyFile = Some(ammonite.ops.Path("/secrets/repl/server_key.key"))
    ),
    predef = """
        |println("Starting repl. Be careful.")
        |import java.time._
      """.stripMargin,
    replArgs = Seq(
      "application" -> this
    )
  )
  replServer.start()
```

When I connect over a kubernetes port forward, I see this from my client:

```
The authenticity of host '[localhost]:12345 ([127.0.0.1]:12345)' can't be established.                   
RSA key fingerprint is SHA256:HLsopysy7kU0zwFz9G6/aelIiXLaNKyuHhVe1LUcWXQ.                               
Are you sure you want to continue connecting (yes/no)? yes                                               
Warning: Permanently added '[localhost]:12345' (RSA) to the list of known hosts.                         
Password authentication                                                                                  
Password:                                                                                                
Compiling (synthetic)/ammonite/predef/interpBridge.sc                                                    
Connection to localhost closed.                                                                          
```

In the server logs, I see:

```
-- log message 1
WARN authenticate(repl[ServerSessionImpl[null@/127.0.0.1:39632]]: accepted without checking

-- log message 2
 INFO Session repl@/127.0.0.1:39632 authenticated
 
 -- log message 3
 WARN handlePtyReq(ChannelSession[id=0, recipient=0]-ServerSessionImpl[repl@/127.0.0.1:39632]) unknown pty opcode value: 42
  java.nio.file.NoSuchFileException: /usr/sbin/.ammonite/cache/1.0.5/compile/ammonite/predef/interpBridge/46daa18064c87fbf456ac8c7fd578eb2/bfc8ebaee777649c6f354c85d3b32384/metadata.json
  	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
  	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
  	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
  	at java.nio.file.Files.newOutputStream(Files.java:216)
  	at ammonite.ops.write$.write(FileOps.scala:278)
  	at ammonite.ops.write$over$.apply(FileOps.scala:316)
  	at ammonite.runtime.Storage$Folder.compileCacheSave(Storage.scala:199)
  	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$5(Interpreter.scala:314)
  	at ammonite.util.Res$Success.map(Res.scala:66)
  	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$3(Interpreter.scala:301)
  	at ammonite.util.Res$Success.flatMap(Res.scala:61)
  	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$2(Interpreter.scala:299)
  	at ammonite.util.Res$Success.flatMap(Res.scala:61)
  	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$1(Interpreter.scala:296)
  	at ammonite.util.Catching.flatMap(Res.scala:114)
  	at ammonite.interp.Interpreter.processSingleBlock(Interpreter.scala:295)
  	at ammonite.interp.Interpreter.$anonfun$processModule$8(Interpreter.scala:372)
  	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$3(Interpreter.scala:499)
  	at ammonite.util.Res$Success.flatMap(Res.scala:61)
  	at ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:486)
  	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:546)
  	at ammonite.util.Res$Success.flatMap(Res.scala:61)
  	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:543)
  	at ammonite.util.Res$Success.flatMap(Res.scala:61)
  	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:540)
  	at scala.Option.getOrElse(Option.scala:121)
  	at ammonite.interp.Interpreter.loop$1(Interpreter.scala:540)
  	at ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:578)
  	at ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:374)
  	at ammonite.util.Catching.flatMap(Res.scala:114)
  	at ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:365)
  	at ammonite.util.Res$Success.flatMap(Res.scala:61)
  	at ammonite.interp.Interpreter.processModule(Interpreter.scala:357)
  	at ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:110)
  	at ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:110)
  	at ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  	at ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  	at scala.collection.immutable.List.foldLeft(List.scala:86)
  	at ammonite.util.Res$.fold(Res.scala:29)
  	at ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  	at ammonite.interp.Interpreter.initializePredef(Interpreter.scala:112)
  	at ammonite.repl.Repl.initializePredef(Repl.scala:115)
  	at ammonite.Main.run(Main.scala:188)
  	at ammonite.sshd.SshdRepl$.$anonfun$runRepl$1(SshdRepl.scala:75)
  	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
  	at scala.Console$.withErr(Console.scala:192)
  	at ammonite.sshd.util.Environment$.$anonfun$withEnvironment$2(Environment.scala:39)
  	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
  	at scala.Console$.withOut(Console.scala:163)
  	at ammonite.sshd.util.Environment$.$anonfun$withEnvironment$1(Environment.scala:38)
  	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
  	at scala.Console$.withIn(Console.scala:226)
  	at ammonite.sshd.util.Environment$.withEnvironment(Environment.scala:37)
  	at ammonite.sshd.SshdRepl$.ammonite$sshd$SshdRepl$$runRepl(SshdRepl.scala:64)
  	at ammonite.sshd.SshdRepl.$anonfun$sshd$1(SshdRepl.scala:32)
  	at ammonite.sshd.SshdRepl.$anonfun$sshd$1$adapted(SshdRepl.scala:32)
  	at ammonite.sshd.ShellSession$$anon$1.run(ShellSession.scala:58)
```

Andy

**Comment by AndyMoreland** [comment]
I ssh'd into the docker container and verified that `/usr/sbin/.ammonite` doesn't exist.

**Comment by AndyMoreland** [comment]
Changing ammoniteHome to a process writable path resolved that issue. There are other issues, but I think they are separate.
