### ISSUE TITLE
Support Scala 2.12.6

### ISSUE THREAD

**Issue by TJSomething** [lihaoyi/Ammonite#803]
I'm using Ammonite as an embedded REPL, but some of the dependencies require scala-reflect 2.12.6, which causes incompatibility with ammonite_2.12.4, causing this exception:

```
java.lang.VerifyError: class scala.tools.nsc.Global overrides final method assert.(ZLscala/Function0;)V
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at scala.tools.nsc.Properties$.pickJarBasedOn(Properties.scala:14)
	at scala.util.PropertiesTrait.scalaProps(Properties.scala:36)
	at scala.util.PropertiesTrait.scalaProps$(Properties.scala:34)
	at scala.tools.nsc.Properties$.scalaProps$lzycompute(Properties.scala:12)
	at scala.tools.nsc.Properties$.scalaProps(Properties.scala:12)
	at scala.util.PropertiesTrait.scalaPropOrNone(Properties.scala:68)
	at scala.util.PropertiesTrait.scalaPropOrNone$(Properties.scala:68)
	at scala.tools.nsc.Properties$.scalaPropOrNone(Properties.scala:12)
	at scala.util.PropertiesTrait.$init$(Properties.scala:80)
	at scala.tools.nsc.Properties$.<init>(Properties.scala:12)
	at scala.tools.nsc.Properties$.<clinit>(Properties.scala)
	at scala.tools.nsc.settings.StandardScalaSettings.$init$(StandardScalaSettings.scala:33)
	at scala.tools.nsc.settings.MutableSettings.<init>(MutableSettings.scala:20)
	at scala.tools.nsc.Settings.<init>(Settings.scala:12)
	at scala.tools.nsc.Settings.<init>(Settings.scala:13)
	at ammonite.interp.CompilerLifecycleManager.$anonfun$init$1(CompilerLifecycleManager.scala:76)
	at scala.Option.fold(Option.scala:158)
	at ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:76)
	at ammonite.interp.CompilerLifecycleManager.preprocess(CompilerLifecycleManager.scala:51)
	at ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:486)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$9(Interpreter.scala:525)
	at scala.Option$WithFilter.map(Option.scala:146)
	at ammonite.interp.Interpreter.loop$1(Interpreter.scala:511)
	at ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:578)
	at ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:374)
	at ammonite.util.Catching.flatMap(Res.scala:114)
	at ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:365)
	at ammonite.util.Res$Success.flatMap(Res.scala:61)
	at ammonite.interp.Interpreter.processModule(Interpreter.scala:357)
	at ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:110)
	at ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:110)
	at ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
	at ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at ammonite.util.Res$.fold(Res.scala:29)
	at ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
	at ammonite.interp.Interpreter.initializePredef(Interpreter.scala:112)
	at ammonite.repl.Repl.initializePredef(Repl.scala:120)
	at ammonite.Main.run(Main.scala:188)
```

**Comment by lihaoyi** [comment]
The latest unstable version `1.1.0-21-ccc8024` should support 2.12.6, you can use that for now until `1.1.1` is released
