### ISSUE TITLE
Failed to compile ammonite with jaotc

### ISSUE THREAD

**Issue by Glavo** [lihaoyi/Ammonite#809]
<pre><font color="#8AE234"><b>glavo@glavo</b></font>:<font color="#729FCF"><b>~/文档/Test</b></font>$ jaotc --ignore-errors --output libamm.so --jar amm.jar 
Exception in thread &quot;main&quot; java.lang.NoClassDefFoundError: jline/console/history/History
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at jdk.aot/jdk.tools.jaotc.collect.ClassSearch.loadClass(ClassSearch.java:56)
	at jdk.aot/jdk.tools.jaotc.collect.ClassSearch.lambda$search$0(ClassSearch.java:48)
	at jdk.aot/jdk.tools.jaotc.collect.jar.JarFileSource.eachClass(JarFileSource.java:48)
	at jdk.aot/jdk.tools.jaotc.collect.ClassSearch.search(ClassSearch.java:48)
	at jdk.aot/jdk.tools.jaotc.Collector.collectClassesToCompile(Collector.java:64)
	at jdk.aot/jdk.tools.jaotc.Main.run(Main.java:134)
	at jdk.aot/jdk.tools.jaotc.Main.run(Main.java:101)
	at jdk.aot/jdk.tools.jaotc.Main.main(Main.java:80)
Caused by: java.lang.ClassNotFoundException: jline.console.history.History
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:890)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 20 more
</pre>

**Comment by lihaoyi** [comment]
This likely never going to work in the forseeable future since jaotc bans runtime classloading and Ammonite is all about runtime classloading
