### ISSUE TITLE
Unable to run ammonite after flushing system cache

### ISSUE THREAD

**Issue by abhi18av** [lihaoyi/Ammonite#849]
Hi @lihaoyi 

Recently due to memory issues, I deleted the Cache contents in my mac and ever since I haven't been able to run `amm` at all.

Here's the error trace 

```
Abhinavs-MacBook-Pro:Caches eklavya$ amm
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/replBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling /Users/eklavya/.ammonite/predef.sc
Compiling /Users/eklavya/.ammonite/predef.sc #2
java.nio.file.NoSuchFileException: /Users/eklavya/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.12/0.5.2/pprint_2.12-0.5.2.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at scala.tools.nsc.classpath.FileBasedCache.$anonfun$getOrCreate$1(ZipAndJarFileLookupFactory.scala:187)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:295)
	at scala.tools.nsc.classpath.FileBasedCache.getOrCreate(ZipAndJarFileLookupFactory.scala:186)
	at scala.tools.nsc.classpath.ZipAndJarFileLookupFactory.createUsingCache(ZipAndJarFileLookupFactory.scala:33)
	at scala.tools.nsc.classpath.ZipAndJarFileLookupFactory.create(ZipAndJarFileLookupFactory.scala:27)
	at scala.tools.nsc.classpath.ZipAndJarFileLookupFactory.create$(ZipAndJarFileLookupFactory.scala:25)
	at scala.tools.nsc.classpath.ZipAndJarClassPathFactory$.create(ZipAndJarFileLookupFactory.scala:41)
	at ammonite.interp.GlobalInitCompat$.$anonfun$initGlobalClasspath$2(GlobalInitCompat.scala:66)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at ammonite.interp.GlobalInitCompat$.initGlobalClasspath(GlobalInitCompat.scala:66)
	at ammonite.interp.Compiler$$anon$2.<init>(Compiler.scala:215)
	at ammonite.interp.Compiler$.apply(Compiler.scala:158)
	at ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:84)
	at ammonite.interp.CompilerLifecycleManager.compileClass(CompilerLifecycleManager.scala:128)
	at ammonite.interp.Interpreter.$anonfun$processSingleBlock$1(Interpreter.scala:297)
	at ammonite.util.Catching.flatMap(Res.scala:114)
	at ammonite.interp.Interpreter.processSingleBlock(Interpreter.scala:295)
	at ammonite.interp.Interpreter.$anonfun$processModule$8(Interpreter.scala:372)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$3(Interpreter.scala:499)
	at ammonite.util.Res$Success.flatMap(Res.scala:61)
	at ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:486)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:546)
	at ammonite.util.Res$Success.flatMap(Res.scala:61)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:543)
	at ammonite.util.Res$Success.flatMap(Res.scala:61)
	at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:540)
	at scala.Option.getOrElse(Option.scala:121)
	at ammonite.interp.Interpreter.loop$1(Interpreter.scala:540)
	at ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:578)
	at ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:374)
	at ammonite.util.Catching.flatMap(Res.scala:114)
	at ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:365)
	at ammonite.util.Res$Success.flatMap(Res.scala:61)
	at ammonite.interp.Interpreter.processModule(Interpreter.scala:355)
	at ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:110)
	at ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:110)
	at ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
	at ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
	at scala.collection.immutable.List.foldLeft(List.scala:86)
	at ammonite.util.Res$.fold(Res.scala:29)
	at ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
	at ammonite.interp.Interpreter.initializePredef(Interpreter.scala:112)
	at ammonite.repl.Repl.initializePredef(Repl.scala:120)
	at ammonite.Main.run(Main.scala:188)
	at ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:370)
	at ammonite.MainRunner.watchLoop(Main.scala:351)
	at ammonite.MainRunner.runRepl(Main.scala:370)
	at ammonite.Main$.main0(Main.scala:287)
	at ammonite.Main$.main(Main.scala:251)
	at ammonite.Main.main(Main.scala)
java.nio.file.NoSuchFileException: /Users/eklavya/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.12/0.5.2/pprint_2.12-0.5.2.jar
  sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
  sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
  sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
  sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
  java.nio.file.Files.readAttributes(Files.java:1737)
  scala.tools.nsc.classpath.FileBasedCache.$anonfun$getOrCreate$1(ZipAndJarFileLookupFactory.scala:187)
  scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
  scala.collection.immutable.List.foreach(List.scala:389)
  scala.collection.TraversableLike.map(TraversableLike.scala:234)
  scala.collection.TraversableLike.map$(TraversableLike.scala:227)
  scala.collection.immutable.List.map(List.scala:295)
  scala.tools.nsc.classpath.FileBasedCache.getOrCreate(ZipAndJarFileLookupFactory.scala:186)
  scala.tools.nsc.classpath.ZipAndJarFileLookupFactory.createUsingCache(ZipAndJarFileLookupFactory.scala:33)
  scala.tools.nsc.classpath.ZipAndJarFileLookupFactory.create(ZipAndJarFileLookupFactory.scala:27)
  scala.tools.nsc.classpath.ZipAndJarFileLookupFactory.create$(ZipAndJarFileLookupFactory.scala:25)
  scala.tools.nsc.classpath.ZipAndJarClassPathFactory$.create(ZipAndJarFileLookupFactory.scala:41)
  ammonite.interp.GlobalInitCompat$.$anonfun$initGlobalClasspath$2(GlobalInitCompat.scala:66)
  scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
  scala.collection.Iterator.foreach(Iterator.scala:944)
  scala.collection.Iterator.foreach$(Iterator.scala:944)
  scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
  scala.collection.IterableLike.foreach(IterableLike.scala:71)
  scala.collection.IterableLike.foreach$(IterableLike.scala:70)
  scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  scala.collection.TraversableLike.map(TraversableLike.scala:234)
  scala.collection.TraversableLike.map$(TraversableLike.scala:227)
  scala.collection.AbstractTraversable.map(Traversable.scala:104)
  ammonite.interp.GlobalInitCompat$.initGlobalClasspath(GlobalInitCompat.scala:66)
  ammonite.interp.Compiler$$anon$2.<init>(Compiler.scala:215)
  ammonite.interp.Compiler$.apply(Compiler.scala:158)
  ammonite.interp.CompilerLifecycleManager.init(CompilerLifecycleManager.scala:84)
  ammonite.interp.CompilerLifecycleManager.compileClass(CompilerLifecycleManager.scala:128)
  ammonite.interp.Interpreter.$anonfun$processSingleBlock$1(Interpreter.scala:297)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.processSingleBlock(Interpreter.scala:295)
  ammonite.interp.Interpreter.$anonfun$processModule$8(Interpreter.scala:372)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$3(Interpreter.scala:499)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:486)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:546)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:543)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:540)
  scala.Option.getOrElse(Option.scala:121)
  ammonite.interp.Interpreter.loop$1(Interpreter.scala:540)
  ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:578)
  ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:374)
  ammonite.util.Catching.flatMap(Res.scala:114)
  ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:365)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.interp.Interpreter.processModule(Interpreter.scala:355)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1(Interpreter.scala:110)
  ammonite.interp.Interpreter.$anonfun$initializePredef$1$adapted(Interpreter.scala:110)
  ammonite.interp.PredefInitialization$.$anonfun$apply$7(PredefInitialization.scala:65)
  ammonite.util.Res$.$anonfun$fold$1(Res.scala:31)
  scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  scala.collection.immutable.List.foldLeft(List.scala:86)
  ammonite.util.Res$.fold(Res.scala:29)
  ammonite.interp.PredefInitialization$.apply(PredefInitialization.scala:53)
  ammonite.interp.Interpreter.initializePredef(Interpreter.scala:112)
  ammonite.repl.Repl.initializePredef(Repl.scala:120)
  ammonite.Main.run(Main.scala:188)
  ammonite.MainRunner.$anonfun$runRepl$1(Main.scala:370)
  ammonite.MainRunner.watchLoop(Main.scala:351)
  ammonite.MainRunner.runRepl(Main.scala:370)
  ammonite.Main$.main0(Main.scala:287)
  ammonite.Main$.main(Main.scala:251)
  ammonite.Main.main(Main.scala)

```

Could you kindly help me out here ?

I have come to rely on ammonite a lot :)

**Comment by abhi18av** [comment]
Further logs 

I've manually been downloading and moving the jars to the location indicated by the error log but now even though `scala-reflect` is there in the correct location, when I try to start the ammonite repl it throws the following error 

```
java.nio.file.NoSuchFileException: /Users/eklavya/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.jar
```

Here's the content of the directory 

```
Abhinavs-MacBook-Pro:2.12.6 eklavya$ pwd
/Users/eklavya/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.6
Abhinavs-MacBook-Pro:2.12.6 eklavya$ ls
scala-reflect-2.12.6-sources.jar
```

**Comment by lihaoyi** [comment]
looks like you need to remove your `~/.ammonite/cache` folder too

**Comment by davoclavo** [comment]
In case someone stumbles upon this issue using ammonite through `mill`:

You have to delete your `~/.mill/ammonite/cache` folder
