### ISSUE TITLE
IllegalAccessError between classes loaded from the same jar.

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [lihaoyi/Ammonite#905]
I have a script that does this:

```
interp.repositories() ++= Seq(
	coursier.MavenRepository("https://jitpack.io"),
	coursier.MavenRepository("https://labs.consol.de/maven/repository")
)
@
import $ivy.`com.sikulix:sikulixapi:1.1.1`
```
It works ok, but sometimes I see errors like this:
```
java.lang.IllegalAccessError: tried to access method org.sikuli.script.Image.purge(Lorg/sikuli/script/ImagePath$PathEntry;)V from class org.sikuli.script.ImagePath
```

I've found a workaround:

I run this:
```
rm -rf ~/.ammonite ~/.cache
```
and magically my script runs again!

It has happened to me several times, and the classes involved in `IllegalAccessError` change.

More info:
- Java 1.8.0_181
- Ammonite 1.3.3.
- CentOS 7

I think this is a bug.

**Comment by DavidPerezIngeniero** [comment]
Another example:
```
java.lang.IllegalAccessError: tried to access method org.sikuli.script.Image.purge(Lorg/sikuli/script/ImagePath$PathEntry;)V from class org.sikuli.script.ImagePath
```

**Comment by DavidPerezIngeniero** [comment]
It happens nearly always with the same class.
It can reappear this bug at any time.

Other people with similar problem:
https://gist.github.com/dyno/2834cd21da70d7777c7887ea0028db15

**Comment by DavidPerezIngeniero** [comment]
I suspect this problem may be caused by the simultaneous execution of 2 or more instances of my script.

**Comment by DavidPerezIngeniero** [comment]
Another conflictive class:
```
java.lang.IllegalAccessError: tried to access class org.sikuli.script.RunTime$1$1 from class org.sikuli.script.RunTime$1
	at org.sikuli.script.RunTime$1.run(RunTime.java:504)
```

**Comment by DavidPerezIngeniero** [comment]
Another case:
```
java.lang.IllegalAccessError: java.lang.IllegalAccessError: tried to access class org.sikuli.script.RunTime$LibsFilter from class org.sikuli.script.RunTime
```

**Comment by DavidPerezIngeniero** [comment]
Simple demo of this bug:
```
#!/usr/bin/env amm
interp.repositories() ++= Seq(
	coursier.MavenRepository("https://jitpack.io"),
	coursier.MavenRepository("https://labs.consol.de/maven/repository")
)
@
import ammonite.ops._
import $ivy.`com.sikulix:sikulixapi:1.1.1`
import $ivy.`org.python:jython-standalone:2.7.1`

@main
def ini() {
	import org.python.util.PythonInterpreter
	import org.sikuli.script.ImagePath
	new PythonInterpreter()
	ImagePath setBundlePath home.toString
}
```

Sometimes it runs ok others fails with this output:
```
[info] runcmd: lsb_release -i -r -s 
[info] runcmd: lsb_release -i -r -s 
java.lang.IllegalAccessError: tried to access method org.sikuli.script.Image.purge(Lorg/sikuli/script/ImagePath$PathEntry;)V from class org.sikuli.script.ImagePath
  org.sikuli.script.ImagePath.setBundlePath(ImagePath.java:561)
  ammonite.$file.bin.kk_2$.ini(kk.sc:16)
  ammonite.$file.bin.kk_2$$routes$.$anonfun$apply$1(kk.sc:26)
  ammonite.main.Router$EntryPoint.invoke(Router.scala:150)
  ammonite.main.Scripts$.runMainMethod(Scripts.scala:194)
  ammonite.main.Scripts$.$anonfun$runScript$5(Scripts.scala:106)
  ammonite.util.Util$.withContextClassloader(Util.scala:16)
  ammonite.main.Scripts$.$anonfun$runScript$4(Scripts.scala:93)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.main.Scripts$.$anonfun$runScript$2(Scripts.scala:67)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.main.Scripts$.$anonfun$runScript$1(Scripts.scala:46)
  ammonite.util.Res$Success.flatMap(Res.scala:61)
  ammonite.main.Scripts$.runScript(Scripts.scala:42)
  ammonite.Main.runScript(Main.scala:224)
  ammonite.MainRunner.$anonfun$runScript$1(Main.scala:369)
  ammonite.MainRunner.watchLoop(Main.scala:355)
  ammonite.MainRunner.runScript(Main.scala:369)
  ammonite.Main$.main0(Main.scala:304)
  ammonite.Main$.main(Main.scala:255)
  ammonite.Main.main(Main.scala)
Exception in thread "Thread-0" java.lang.IllegalAccessError: tried to access class org.sikuli.script.RunTime$1$1 from class org.sikuli.script.RunTime$1
	at org.sikuli.script.RunTime$1.run(RunTime.java:504)
```
