### ISSUE TITLE
cannot build from release archive

### ISSUE THREAD

**Issue by dlaflamme** [lihaoyi/Ammonite#947]
Tried .tar.gz distribution for both 1.6.1 and 1.6.5.

[dan@host Ammonite-1.6.1]$ sbt clean compile package
[info] Loading project definition from /home/dan/tmp/Ammonite-1.6.1/project
[info] Updating {file:/home/dan/tmp/Ammonite-1.6.1/project/}ammonite-1-6-1-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to ammonite-1-6-1 (in build file:/home/dan/tmp/Ammonite-1.6.1/)
[info] Executing in batch mode. For better performance use sbt's shell
[success] Total time: 0 s, completed Mar 29, 2019 11:53:47 PM
Generating Scalatex Sources...
[info] Updating {file:/home/dan/tmp/Ammonite-1.6.1/}readme...
[info] Updating {file:/home/dan/tmp/Ammonite-1.6.1/}ammonite-1-6-1...
[info] Resolving jline#jline;2.14.4 ...
[info] Done updating.
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.util.NoSuchElementException: key not found: CONSTANTS_FILE
        at scala.collection.MapLike$class.default(MapLike.scala:228)
        at scala.collection.AbstractMap.default(Map.scala:58)
        at scala.collection.MapLike$class.apply(MapLike.scala:141)
        at scala.collection.AbstractMap.apply(Map.scala:58)
        at $fc996592160a746a5ce3$$anonfun$readme$6.apply(build.sbt:17)
        at $fc996592160a746a5ce3$$anonfun$readme$6.apply(build.sbt:17)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (readme/compile:unmanagedSources) java.util.NoSuchElementException: key not found: CONSTANTS_FILE
[error] Total time: 0 s, completed Mar 29, 2019 11:53:47 PM
[dan@host Ammonite-1.6.1]$

**Comment by lihaoyi** [comment]
Ammonite isn't built using SBT

**Comment by dlaflamme** [comment]
Apparently. Thanks.

Here is why someone might think that it was:

- assuming sbt is a good default option for scala projects
- there is a file called build.sbt in the unpacked release directory
- sbt is mentioned in the readme to run the integration tests

Maybe it would be useful to add a short section on how to build the project to the readme.

**Comment by nbauernfeind** [comment]
Thanks for letting future readers know how to kick off a local build...

**Comment by nbauernfeind** [comment]
To future readers, this project uses `mill` another project by the primary author.
This blog post got me started: https://www.lihaoyi.com/post/MillBetterScalaBuilds.html

I wanted to publish artifacts locally for scala 2.13.6 to see if I can find a proposal to fix #1206. This did the trick for me and might help another who has never heard of mill before.
```bash
./mill '__[2.13.6].publishLocal'
```
