### ISSUE TITLE
StringIndexOutOfBoundsException with nested scripts

### ISSUE THREAD

**Issue by padhia** [lihaoyi/Ammonite#950]
I am using Scala 2.12.8, OpenJDK 1.8.0_212 and ammonite version 1.6.5 on Manjaro Linux. I have a strange behavior when nesting script files.

I have two files as follows

**a.sc**
```scala
case class A(x: String)
```

**b.sc**
```scala
#! /usr/bin/env amm
import $file.a, a._
println("hello world")
```

`b.sc` is made executable. When I invoke `b.sc` directly from `bash` prompt, it fails with following exception.
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.String.charAt(String.java:658)
        at ammonite.util.Name.<init>(Model.scala:56)
        at ammonite.interp.AmmonitePlugin$.$anonfun$apply$10(AmmonitePlugin.scala:198)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
        at scala.collection.TraversableLike.map(TraversableLike.scala:237)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
        at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
        at ammonite.interp.AmmonitePlugin$.$anonfun$apply$9(AmmonitePlugin.scala:198)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:89)
        at ammonite.interp.AmmonitePlugin$.apply(AmmonitePlugin.scala:164)
        at ammonite.interp.AmmonitePlugin$$anon$1$$anon$2.apply(AmmonitePlugin.scala:36)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
        at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1580)
        at ammonite.interp.Compiler$$anon$2.compile(Compiler.scala:342)
        at ammonite.interp.CompilerLifecycleManager.compileClass(CompilerLifecycleManager.scala:130)
        at ammonite.interp.Interpreter.$anonfun$processSingleBlock$2(Interpreter.scala:309)
        at ammonite.util.Catching.flatMap(Res.scala:114)
        at ammonite.interp.Interpreter.processSingleBlock(Interpreter.scala:307)
        at ammonite.interp.Interpreter.$anonfun$processModule$8(Interpreter.scala:384)
        at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$3(Interpreter.scala:511)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.interp.Interpreter.compileRunBlock$1(Interpreter.scala:498)
        at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$15(Interpreter.scala:558)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$14(Interpreter.scala:555)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.interp.Interpreter.$anonfun$processAllScriptBlocks$12(Interpreter.scala:552)
        at scala.Option.getOrElse(Option.scala:138)
        at ammonite.interp.Interpreter.loop$1(Interpreter.scala:552)
        at ammonite.interp.Interpreter.processAllScriptBlocks(Interpreter.scala:590)
        at ammonite.interp.Interpreter.$anonfun$processModule$6(Interpreter.scala:386)
        at ammonite.util.Catching.flatMap(Res.scala:114)
        at ammonite.interp.Interpreter.$anonfun$processModule$5(Interpreter.scala:377)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.interp.Interpreter.processModule(Interpreter.scala:367)
        at ammonite.main.Scripts$.$anonfun$runScript$1(Scripts.scala:46)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at ammonite.main.Scripts$.runScript(Scripts.scala:42)
        at ammonite.Main.runScript(Main.scala:213)
        at ammonite.MainRunner.$anonfun$runScript$1(Main.scala:358)
        at ammonite.MainRunner.watchLoop(Main.scala:344)
        at ammonite.MainRunner.runScript(Main.scala:358)
        at ammonite.Main$.main0(Main.scala:293)
        at ammonite.Main$.main(Main.scala:244)
        at ammonite.Main.main(Main.scala)
```

However, `amm b.sc` works just fine. 

I am new to Scala and ammonite, so not sure if I am doing something wrong. 

Has anyone encountered this issue before?

**Comment by padhia** [comment]
I think I now know the circumstances under which this problem occurs. If any segment of the script's path contains `.` (period) and if the script is invoked outside the directory hierarchy that contains the segment with `.`, it then fails with the error reported earlier.

Following sequence of steps will illustrate the issue:

1. create a folder `mkdir -p /tmp/.my/bin`
2. create `a.sc` and `b.sc` files as shown above in this folder
3. Run 1 (works)
    3.1. change working directory to `cd /tmp/.my`
    3.2. Try `/tmp/.my/bin/b.sc` 
4. Run 2 (**fails**)
    4.1. change working directory to `cd /tmp`
    4.2  Try `/tmp/.my/bin/b.sc`

**Comment by lolgab** [comment]
We are splitting the import by the `.` char [here](https://github.com/com-lihaoyi/Ammonite/blob/99cfa4e262b2580e4bf6d12dee6b8ef75b149aea/amm/compiler/src/main/scala-3/ammonite/compiler/AmmonitePhase.scala#L100).
This doesn't work since we need to distinguish subpaths and earlier, when we go from `../.my/bin` to `import $file.^..my.bin`, we should, instead, convert to something like `import $file.^.$dot$my.bin` to distinguish a dot in the name from the dot as a separator of directories.
